In [2]:
# homework 4 - valuation

In [3]:
# imports 

from tqdm.auto import tqdm

In [4]:
# generating data

In [5]:
from gitsource import GithubRepositoryDataReader

reader = GithubRepositoryDataReader(
    repo_owner="DataTalksClub",
    repo_name="llm-zoomcamp",
    commit_id="8c1834d",
    allowed_extensions={"md"},
    filename_filter=lambda path: "/lessons/" in path,
)
documents = [file.parse() for file in reader.read()]

print(len(documents))
documents[0]

72

{'content': '# Introduction\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=rQYyFxf1FWw&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn this module, we\'ll build a working Retrieval-Augmented\nGeneration (RAG) system from scratch, step by step.\n\nWe write everything in plain Python. We build a small search index by\nhand and call the LLM ourselves. I want you to see every piece first.\nThat way you know what a framework does for you before you reach for\none.\n\nPlaces where you can find me:\n\n- [My substack](https://alexeyondata.substack.com/)\n- [LinkedIn](https://www.linkedin.com/in/agrigorev/)\n- [X](https://x.com/Al_Grigor)\n\n## LLMs\n\nAn LLM (Large Language Model) is a neural network trained on massive\namounts of text. Given a prompt, it generates a continuation - a\nplausible next piece of text.\n\nThink of your phone. When you type "how are" in WhatsApp, it suggests\n"you" as the next word. "How are you" is the most common continuation.\nYour phone uses a simple language model for that. It predicts the next\nword based on what you typed so far.\n\nA large language model does the same thing, but at a much larger scale.\nIt has billions of parameters and is trained on most of the text on the\ninternet. When it predicts the next word, it feels like you\'re talking\nto an intelligent being. It understands what you ask and gives\nmeaningful answers.\n\nIn this course, we treat LLMs as black boxes. We won\'t look inside or\ncover the theory, and we won\'t host a model ourselves. We use an LLM\nprovider and call it over an API. For us, an LLM is a box: text goes in,\ntext comes out.\n\nBut LLMs have limitations:\n\n- Knowledge cutoff: they only know what was in their training data.\n  If you ask about something that happened after training, they won\'t\n  know - or worse, they\'ll make something up.\n- No access to your data: they can\'t see your documents, databases,\n  or internal systems unless you provide that information.\n- Hallucinations: they sometimes produce confident-sounding answers\n  that are simply wrong.\n\n## The project\n\nRAG solves these problems by giving the LLM relevant documents at\nquestion time. We don\'t hope the model memorized the answer. We\nretrieve the right information and hand it to the LLM, and the model\ngenerates a grounded response. This lets us inject knowledge the model\nnever saw during training. That\'s why RAG is still the most common way\npeople use LLMs in the industry.\n\nTo make this concrete, we build a FAQ agent for our course. A student\nasks something like "when does the course start?" and the agent answers\nfrom the FAQ data we prepared.\n\nThis module has two parts.\n\nIn Part 1 (the next 9 lessons) we will:\n\n- Understand what RAG is and how it works\n- Build a search engine over a real FAQ dataset\n- Write a prompt that combines the user\'s question with search results\n- Wire it all together into a working RAG pipeline\n- Split ingestion and query into separate processes\n\nIn Part 2, we make the pipeline agentic. The LLM decides when and\nwhat to search, instead of running the same fixed flow every time.\n\nThe final code from this module is available in the\n[code/](../code/) directory.\n\n[← Back to module](../) | [Environment →](02-environment.md)',
 'filename': '01-agentic-rag/lessons/01-intro.md'}

In [6]:
# we want structured output and define structured data using pydantic:

from pydantic import BaseModel

class Questions(BaseModel):
    questions: list[str]


# instructions for the llm: 
data_gen_instructions = """
You emulate a student who is taking our LLM course.
You are given one lesson page from the course.
Formulate 5 questions this student might ask that are answered by this page.

Rules:
- The page should contain the answer to each question.
- Make the questions complete and not too short.
- Use as few words as possible from the page; don't copy its phrasing.
- The questions should resemble how people actually ask things online:
  not too formal, not too short, not too long.
- Ask about the content of the lesson, not about its formatting or filename.
""".strip()

In [7]:
# initialize openai: 

from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
openai_client = OpenAI()

In [8]:
# if something goes temporarily wrong e.g. due to a temporary or network issue, then retry

from evaluation_utils import llm_structured_retry

# we will se it in the processing function: 

def generate_ground_truth(doc):
    import json
    user_prompt = json.dumps(doc)

    out, usage = llm_structured_retry(
        openai_client,
        data_gen_instructions,
        user_prompt,
        Questions
    )

    results = []

    for q in out.questions:
        results.append({
            "question": q,
            "document": doc["filename"]
        })

    return results, usage

In [9]:
# Parallel processing with 5 or 6 connections at once

# it is possible because we are just waiting for a response from openai
# we want to be a little carefult to not hit the provider limits somehow


# threadpoolexecutor allows us to have different workers, 
# we will have thread 1, thead 2, thread 3, ... each of these threads 
# will be an executor that is pulling of this common task pool. 

# then we iterate over this things, submit to the output executor, 
# thread pool executor is evaluating them and we get bakc the responses 

from concurrent.futures import ThreadPoolExecutor
from evaluation_utils import map_progress

# using it is very simple:
# we create this threat pool we say that we want at most 6 workders and then 
# we use this function

with ThreadPoolExecutor(max_workers=6) as pool:
    results = map_progress(
        pool,
        documents,
        generate_ground_truth
    )

  0%|          | 0/72 [00:00<?, ?it/s]

In [10]:
results[0]

([{'question': 'What is RAG, and how does it help an LLM answer questions better?',
   'document': '01-agentic-rag/lessons/01-intro.md'},
  {'question': 'Why do we treat the language model as a black box in this course instead of building one ourselves?',
   'document': '01-agentic-rag/lessons/01-intro.md'},
  {'question': 'What kinds of problems do LLMs have that make retrieval useful, like cutoff knowledge or hallucinations?',
   'document': '01-agentic-rag/lessons/01-intro.md'},
  {'question': 'What are we building in this module, and what kind of FAQ example will it use?',
   'document': '01-agentic-rag/lessons/01-intro.md'},
  {'question': 'What will be covered in the first part versus the second part of this RAG module?',
   'document': '01-agentic-rag/lessons/01-intro.md'}],
 ResponseUsage(input_tokens=1020, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=110, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=1130))

In [11]:
# split data and usage into different lists: 

# extent (everything)
# append (just one)
ground_truth = []
usages = []

for records, usage in results:
    ground_truth.extend(records)
    usages.append(usage)

len(ground_truth)

360

In [12]:
# calc usage price ... 
# price helper: 
from evaluation_utils import calc_total_price

calc_total_price(usages)

0.1134

In [13]:
# turn all this into a pandas document so we can look at it and 
# also download it 

import pandas as pd

df_ground_truth = pd.DataFrame(ground_truth)

In [14]:
df_ground_truth

,question,document
0,"What is RAG, and how does it help an LLM answe...",01-agentic-rag/lessons/01-intro.md
1,Why do we treat the language model as a black ...,01-agentic-rag/lessons/01-intro.md
2,What kinds of problems do LLMs have that make ...,01-agentic-rag/lessons/01-intro.md
3,"What are we building in this module, and what ...",01-agentic-rag/lessons/01-intro.md
4,What will be covered in the first part versus ...,01-agentic-rag/lessons/01-intro.md
...,...,...
355,How should I handle retrieval if my source is ...,07-project-example/lessons/07-chunking.md
356,What’s the recommended way to break up one lon...,07-project-example/lessons/07-chunking.md
357,"For books or other very long material, should ...",07-project-example/lessons/07-chunking.md
358,How can slide decks or images be turned into s...,07-project-example/lessons/07-chunking.md
359,"What does semantic or logical chunking mean, a...",07-project-example/lessons/07-chunking.md

In [15]:
df_ground_truth.to_csv("data/ground-truth-course-lessons.csv", index=False)

In [16]:
"""
Q1. Generating questions
Generating questions for all 72 pages costs money and takes time, so let's start small and generate questions for just the first 3 pages:

01-agentic-rag/lessons/01-intro.md
01-agentic-rag/lessons/02-environment.md
01-agentic-rag/lessons/03-rag.md
Each call returns the token usage, which most LLM APIs report on the response object (e.g. response.usage.input_tokens / prompt_tokens).

What's the average number of input tokens across these 3 calls?

140
1400
14000
140000
These numbers vary between runs, even with the same model, so pick the closest option. A different provider or model may land further apart, but the input tokens stay in the same order of magnitude - the prompt we send is the same.
"""

"\nQ1. Generating questions\nGenerating questions for all 72 pages costs money and takes time, so let's start small and generate questions for just the first 3 pages:\n\n01-agentic-rag/lessons/01-intro.md\n01-agentic-rag/lessons/02-environment.md\n01-agentic-rag/lessons/03-rag.md\nEach call returns the token usage, which most LLM APIs report on the response object (e.g. response.usage.input_tokens / prompt_tokens).\n\nWhat's the average number of input tokens across these 3 calls?\n\n140\n1400\n14000\n140000\nThese numbers vary between runs, even with the same model, so pick the closest option. A different provider or model may land further apart, but the input tokens stay in the same order of magnitude - the prompt we send is the same.\n"

In [17]:
# generate_ground_truth(doc)

total_input_tokens = 0

first_three_pages = documents[:3]
for page in first_three_pages:
    print("processing: ", page["filename"])
    results, usage = generate_ground_truth(page)
    total_input_tokens += usage.input_tokens
    print("Usage: ", usage)


print("total input tokens: ", total_input_tokens)
print("avg total_input_tokens: ", total_input_tokens / 3)


# SOLUTION: 1350.0 -> CLOSEST ANSWER: 1400

processing:  01-agentic-rag/lessons/01-intro.md
Usage:  ResponseUsage(input_tokens=1020, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=125, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=1145)
processing:  01-agentic-rag/lessons/02-environment.md
Usage:  ResponseUsage(input_tokens=1286, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=125, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=1411)
processing:  01-agentic-rag/lessons/03-rag.md
Usage:  ResponseUsage(input_tokens=1753, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=1280), output_tokens=100, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=1853)
total input tokens:  4059
avg total_input_tokens:  1353.0

In [18]:
"""
The full ground truth
You don't need to generate the data for the rest of the homework. We already did it for all 72 pages, using the same approach as in the lessons, and saved the 360 questions to a file.

Download it:

PREFIX=https://raw.githubusercontent.com/DataTalksClub/llm-zoomcamp/main
wget ${PREFIX}/cohorts/2026/04-evaluation/ground-truth.csv
Load it with pandas into a dataframe of records called ground_truth. Each record has a question and the filename of the page that should answer it.
"""


# !PREFIX=https://raw.githubusercontent.com/DataTalksClub/llm-zoomcamp/main
# !wget ${PREFIX}/cohorts/2026/04-evaluation/ground-truth.csv

ground_truth = pd.read_csv("ground-truth.csv")
ground_truth.head(5)

,question,filename
0,What exactly is a retrieval-augmented generati...,01-agentic-rag/lessons/01-intro.md
1,Why does this course build the RAG project in ...,01-agentic-rag/lessons/01-intro.md
2,What are the main weaknesses of large language...,01-agentic-rag/lessons/01-intro.md
3,What will the course build in the first part o...,01-agentic-rag/lessons/01-intro.md
4,What kind of example app are you building here...,01-agentic-rag/lessons/01-intro.md

In [19]:
ground_truth = ground_truth.to_dict(orient="records")

In [20]:
"""
Searching the chunks
We search over the same chunks as in homework 2.

Create them with chunk_documents:

from gitsource import chunk_documents

chunks = chunk_documents(documents, size=2000, step=1000)
This gives 295 chunks.

Now rebuild the search from homework 2 over these chunks. Build a text index (Index) and a vector index (VectorSearch), both keyed on filename. Wrap each one in a function, text_search and vector_search, that takes a query and the number of results to return (5 by default).

For hybrid search, reuse the rrf function from homework 2:

def rrf(result_lists, k=60, num_results=5):
    scores = {}
    docs = {}

    for results in result_lists:
        for rank, doc in enumerate(results):
            key = (doc["filename"], doc["start"])
            scores[key] = scores.get(key, 0) + 1 / (k + rank)
            docs[key] = doc

    ranked = sorted(scores, key=scores.get, reverse=True)
    return [docs[key] for key in ranked[:num_results]]
Then define hybrid_search on top of it:

def hybrid_search(query, k=60):
    text_results = text_search(query, num_results=10)
    vector_results = vector_search(query, num_results=10)
    return rrf([text_results, vector_results], k=k)
"""

'\nSearching the chunks\nWe search over the same chunks as in homework 2.\n\nCreate them with chunk_documents:\n\nfrom gitsource import chunk_documents\n\nchunks = chunk_documents(documents, size=2000, step=1000)\nThis gives 295 chunks.\n\nNow rebuild the search from homework 2 over these chunks. Build a text index (Index) and a vector index (VectorSearch), both keyed on filename. Wrap each one in a function, text_search and vector_search, that takes a query and the number of results to return (5 by default).\n\nFor hybrid search, reuse the rrf function from homework 2:\n\ndef rrf(result_lists, k=60, num_results=5):\n    scores = {}\n    docs = {}\n\n    for results in result_lists:\n        for rank, doc in enumerate(results):\n            key = (doc["filename"], doc["start"])\n            scores[key] = scores.get(key, 0) + 1 / (k + rank)\n            docs[key] = doc\n\n    ranked = sorted(scores, key=scores.get, reverse=True)\n    return [docs[key] for key in ranked[:num_results]]\nThen define hybrid_search on top of it:\n\ndef hybrid_search(query, k=60):\n    text_results = text_search(query, num_results=10)\n    vector_results = vector_search(query, num_results=10)\n    return rrf([text_results, vector_results], k=k)\n'

In [21]:
from gitsource import chunk_documents

chunks = chunk_documents(documents, size=2000, step=1000)

# len = 295

In [22]:
chunks[:5]

[{'start': 0,
  'content': '# Introduction\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=rQYyFxf1FWw&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn this module, we\'ll build a working Retrieval-Augmented\nGeneration (RAG) system from scratch, step by step.\n\nWe write everything in plain Python. We build a small search index by\nhand and call the LLM ourselves. I want you to see every piece first.\nThat way you know what a framework does for you before you reach for\none.\n\nPlaces where you can find me:\n\n- [My substack](https://alexeyondata.substack.com/)\n- [LinkedIn](https://www.linkedin.com/in/agrigorev/)\n- [X](https://x.com/Al_Grigor)\n\n## LLMs\n\nAn LLM (Large Language Model) is a neural network trained on massive\namounts of text. Given a prompt, it generates a continuation - a\nplausible next piece of text.\n\nThink of your phone. When you type "how are" in WhatsApp, it suggests\n"you" as the next word. "How are you" is the most common continuation.\nYour phone uses a simple language model for that. It predicts the next\nword based on what you typed so far.\n\nA large language model does the same thing, but at a much larger scale.\nIt has billions of parameters and is trained on most of the text on the\ninternet. When it predicts the next word, it feels like you\'re talking\nto an intelligent being. It understands what you ask and gives\nmeaningful answers.\n\nIn this course, we treat LLMs as black boxes. We won\'t look inside or\ncover the theory, and we won\'t host a model ourselves. We use an LLM\nprovider and call it over an API. For us, an LLM is a box: text goes in,\ntext comes out.\n\nBut LLMs have limitations:\n\n- Knowledge cutoff: they only know what was in their training data.\n  If you ask about something that happened after training, they won\'t\n  know - or worse, they\'ll make something up.\n- No access to your data: they can\'t see your documents, databases,\n  or internal systems unless you provide that information.\n- Hallucinations: they sometimes produce confident-sounding answers\n  that are simply ',
  'filename': '01-agentic-rag/lessons/01-intro.md'},
 {'start': 1000,
  'content': 'the next\nword based on what you typed so far.\n\nA large language model does the same thing, but at a much larger scale.\nIt has billions of parameters and is trained on most of the text on the\ninternet. When it predicts the next word, it feels like you\'re talking\nto an intelligent being. It understands what you ask and gives\nmeaningful answers.\n\nIn this course, we treat LLMs as black boxes. We won\'t look inside or\ncover the theory, and we won\'t host a model ourselves. We use an LLM\nprovider and call it over an API. For us, an LLM is a box: text goes in,\ntext comes out.\n\nBut LLMs have limitations:\n\n- Knowledge cutoff: they only know what was in their training data.\n  If you ask about something that happened after training, they won\'t\n  know - or worse, they\'ll make something up.\n- No access to your data: they can\'t see your documents, databases,\n  or internal systems unless you provide that information.\n- Hallucinations: they sometimes produce confident-sounding answers\n  that are simply wrong.\n\n## The project\n\nRAG solves these problems by giving the LLM relevant documents at\nquestion time. We don\'t hope the model memorized the answer. We\nretrieve the right information and hand it to the LLM, and the model\ngenerates a grounded response. This lets us inject knowledge the model\nnever saw during training. That\'s why RAG is still the most common way\npeople use LLMs in the industry.\n\nTo make this concrete, we build a FAQ agent for our course. A student\nasks something like "when does the course start?" and the agent answers\nfrom the FAQ data we prepared.\n\nThis module has two parts.\n\nIn Part 1 (the next 9 lessons) we will:\n\n- Understand what RAG is and how it works\n- Build a search engine over a real FAQ dataset\n- Write a prompt that combines the user\'s question with search results\n- Wire it all together into a working RAG pipeline\n- Split ingestion and query into separate processes\n\nIn Part 2, we make the pipeline agentic. The LLM decides when and\nwhat to search, instead of ',
  'filename': '01-agentic-rag/lessons/01-intro.md'},
 {'start': 2000,
  'content': 'wrong.\n\n## The project\n\nRAG solves these problems by giving the LLM relevant documents at\nquestion time. We don\'t hope the model memorized the answer. We\nretrieve the right information and hand it to the LLM, and the model\ngenerates a grounded response. This lets us inject knowledge the model\nnever saw during training. That\'s why RAG is still the most common way\npeople use LLMs in the industry.\n\nTo make this concrete, we build a FAQ agent for our course. A student\nasks something like "when does the course start?" and the agent answers\nfrom the FAQ data we prepared.\n\nThis module has two parts.\n\nIn Part 1 (the next 9 lessons) we will:\n\n- Understand what RAG is and how it works\n- Build a search engine over a real FAQ dataset\n- Write a prompt that combines the user\'s question with search results\n- Wire it all together into a working RAG pipeline\n- Split ingestion and query into separate processes\n\nIn Part 2, we make the pipeline agentic. The LLM decides when and\nwhat to search, instead of running the same fixed flow every time.\n\nThe final code from this module is available in the\n[code/](../code/) directory.\n\n[← Back to module](../) | [Environment →](02-environment.md)',
  'filename': '01-agentic-rag/lessons/01-intro.md'},
 {'start': 0,
  'content': '# Environment\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=3U4gBrmkZyM&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nFor this module, all you need is Python with Jupyter.\n\n## Prerequisites\n\nYou need the following:\n\n- Python (3.14 or later)\n- An [OpenAI account](https://openai.com/) (or an OpenAI-compatible\n  provider like Groq, Gemini, or Ollama)\n- Basic familiarity with Python and the command line\n\n## Creating the project\n\nWe\'ll start from scratch - no cloning needed. You\'ll create the\nproject yourself, step by step.\n\nFirst, install uv. It\'s a Python package manager, and I switched all my\nprojects to it because it\'s fast and convenient. Once I started using\nit, I never wanted to go back.\n\nOn Mac or Linux:\n\n```bash\ncurl -LsSf https://astral.sh/uv/install.sh | sh\n```\n\nOn Windows:\n\n```powershell\npowershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"\n```\n\n(You can also use `pip install uv` if you prefer.)\n\nCreate an empty folder for the project and initialize it:\n\n```bash\nmkdir llm-zoomcamp-code\ncd llm-zoomcamp-code\nuv init\n```\n\nThis creates a `pyproject.toml` and a basic project structure.\n\nNow add the dependencies we\'ll need:\n\n```bash\nuv add requests minsearch openai jupyter python-dotenv\n```\n\nThis installs:\n\n- `requests` - to fetch the FAQ dataset from the internet\n- `minsearch` - a simple in-memory search engine for indexing and\n  searching text\n- `openai` - the OpenAI API client for calling the LLM\n- `jupyter` - the notebook environment where we\'ll write and run code\n- `python-dotenv` - to load API keys from a `.env` file\n\n## Setting up API keys\n\nWe need an API key to talk to the LLM. If you\'re using OpenAI, you\'ll\nneed to deposit some money first. The minimum is $5 (as of June 2026).\nThis lesson costs well under 10 cents to run, so that $5 goes a long\nway.\n\nI also recommend creating a separate OpenAI project for the course.\nThen you can open the usage page and see exactly how much you spent\nhere, apart from your other work.\n',
  'filename': '01-agentic-rag/lessons/02-environment.md'},
 {'start': 1000,
  'content': "nitialize it:\n\n```bash\nmkdir llm-zoomcamp-code\ncd llm-zoomcamp-code\nuv init\n```\n\nThis creates a `pyproject.toml` and a basic project structure.\n\nNow add the dependencies we'll need:\n\n```bash\nuv add requests minsearch openai jupyter python-dotenv\n```\n\nThis installs:\n\n- `requests` - to fetch the FAQ dataset from the internet\n- `minsearch` - a simple in-memory search engine for indexing and\n  searching text\n- `openai` - the OpenAI API client for calling the LLM\n- `jupyter` - the notebook environment where we'll write and run code\n- `python-dotenv` - to load API keys from a `.env` file\n\n## Setting up API keys\n\nWe need an API key to talk to the LLM. If you're using OpenAI, you'll\nneed to deposit some money first. The minimum is $5 (as of June 2026).\nThis lesson costs well under 10 cents to run, so that $5 goes a long\nway.\n\nI also recommend creating a separate OpenAI project for the course.\nThen you can open the usage page and see exactly how much you spent\nhere, apart from your other work.\n\nThe safest way to store the key is in a `.env` file that never gets\ncommitted to git.\n\nCreate a `.env` file in your project folder and put your API key in\nit:\n\n```bash\nOPENAI_API_KEY=sk-YOUR_KEY_HERE\n```\n\nNow add `.env` to `.gitignore` to make sure you never accidentally\ncommit your key:\n\n```bash\n.env\n```\n\nNever commit `.env` to git. Treat the API key like a password. If it\nleaks, someone else can run up charges on your account.\n\n## Starting Jupyter\n\nStart Jupyter:\n\n```bash\nuv run jupyter notebook\n```\n\nCreate a new notebook. Throughout the course, you'll copy code from\nthe section notes into notebook cells.\n\nCheck that the OpenAI client works:\n\n```python\nfrom dotenv import load_dotenv\nload_dotenv()\n\nfrom openai import OpenAI\nopenai_client = OpenAI()\n```\n\nIf you see an error, make sure the key in your `.env` file is\ncorrect.\n\nFor Groq or other OpenAI-compatible providers, add the key to\n`.env`:\n\n```bash\nGROQ_API_KEY=your_key_here\n```\n\nAnd configure the client:\n\n```python\nfrom openai im",
  'filename': '01-agentic-rag/lessons/02-environment.md'}]

In [23]:
# Build a text index (Index), keyed on filename. Wrap in a function, that takes a query and the number of results to return (5 by default).


def build_index(documents):
    from minsearch import Index
    index = Index(
        text_fields=['content'],
        keyword_fields=['filename']
    )
    index.fit(documents)
    return index

index = build_index(documents=chunks)

def text_search(query, num_results=5):
    # the question boost is 3.0 if the user question matches exactly the faq then its more important
    # boost_dict = {"question": 3.0, "section": 0.5}

    return index.search(
        query,
        num_results=num_results,
        # boost_dict=boost_dict
    )

example_text_search = text_search("What wheather is today?")
example_text_search

[{'start': 4000,
  'content': '\nCall the LLM for one document:\n\n```python\nfrom dotenv import load_dotenv\nfrom openai import OpenAI\n\nload_dotenv()\nopenai_client = OpenAI()\n```\n\nPrepare the document as JSON:\n\n```python\nimport json\n\nuser_prompt = json.dumps(doc)\n```\n\nCreate the messages:\n\n```python\nmessages = [\n    {"role": "developer", "content": data_gen_instructions},\n    {"role": "user", "content": user_prompt}\n]\n```\n\nUntil now we called `responses.create` and read `response.output_text`.\nFor structured output we switch to `responses.parse` and pass\n`text_format=Questions`, which tells the API to return our class instead\nof free text.\n\nCall the model:\n\n```python\nresponse = openai_client.responses.parse(\n    model="gpt-5.4-mini",\n    input=messages,\n    text_format=Questions\n)\n```\n\nThe parsed object is available in `response.output_parsed`:\n\n```python\nresult = response.output_parsed\n\nprint(result)\n```\n\nWe can access the list directly:\n\n```python\nprint(result.questions)\n```\n\nYou should see 5 questions that relate to the first FAQ document.\n\n## Reusable utilities\n\nWe\'ll need this pattern again in other evaluation sections today, so\nwe put it in a reusable helper.\n\nIt contains helper functions we\'ll reuse in this module:\n\n- `llm_structured`: calls the OpenAI API with structured output\n- `llm_structured_retry`: retries structured-output calls when a\n  request fails\n- `calc_price`: calculates the price from token usage\n- `calc_total_price`: calculates the total price from multiple usage\n  objects\n- `map_progress`: runs work in parallel and tracks progress. We\'ll use it\n  in the next lesson.\n\nImport the structured-output helper:\n\n```python\nfrom evaluation_utils import llm_structured\n```\n\nUse it on the same document:\n\n```python\nresult, usage = llm_structured(\n    openai_client,\n    data_gen_instructions,\n    user_prompt,\n    Questions\n)\n\nprint(result.questions)\n```\n\n## Tracking cost\n\nThe response also contains token usage:\n\n```python\nusage.input_tokens, usage.output_tokens\n```\n\nAs in the agents module, ',
  'filename': '04-evaluation/lessons/02-ground-truth.md'},
 {'start': 3000,
  'content': 'we drop it.\n\nBuild a prompt that includes both the question and the context:\n\n```python\nprompt = f"""\nYour task is to answer questions from the course participants\nbased on the provided context.\n\nUse the context to find relevant information and provide accurate\nanswers. If the answer is not found in the context,\nrespond with "I don\'t know."\n\nQuestion:\n{question}\n\nContext:\n{context}\n"""\n```\n\nInstead of sending the raw question to the LLM, we send this prompt:\n\n```python\nanswer = llm(prompt)\nprint(answer)\n```\n\nAfter that, the answer is correct: "Yes, you can still join. If you want to\nreceive a certificate, you need to submit your project while\nsubmissions are still open."\n\nThis is the answer we actually want to give to our students. What we\njust did is nothing but RAG.\n\n## Retrieval plus generation\n\nRAG stands for Retrieval-Augmented Generation. Generation is the LLM\nproducing text, and retrieval is search. We retrieve relevant documents\nfrom our knowledge base and use them to augment what the LLM generates.\nThat search step is what gives the LLM the context it needs to answer\ncorrectly.\n\nWhat we just did was naive. I knew in advance which FAQ entry held the\nanswer and pasted it in by hand. What we want instead is to perform\nsearch automatically. We take the student\'s question, find the most\nrelevant documents, and send those to the LLM.\n\nIn code, it looks like this:\n\n```python\ndef rag(question):\n    search_results = search(question)\n    user_prompt = build_prompt(question, search_results)\n    return llm(user_prompt)\n```\n\nThat\'s the entire architecture. It comes down to three components.\n\nThe pieces are search, the prompt, and the LLM:\n\n- search\n- prompt\n- LLM\n\n\n```mermaid\nflowchart TD\n    U([User])\n\n    APP[Application]\n\n    DB[(DB)]\n    DOCS[[D1 ... D5]]\n\n    PROMPT[Build Prompt<br/>Question + Context]\n\n    LLM[LLM]\n\n    ANSWER([Answer])\n\n    U -->|Question| APP\n\n    APP -->|Query| DB\n    DB -->|Retrieved Data| DOCS\n    DOCS --> APP\n\n    APP --> PROMPT\n    PROMPT -',
  'filename': '01-agentic-rag/lessons/03-rag.md'},
 {'start': 5000,
  'content': 'the first FAQ document.\n\n## Reusable utilities\n\nWe\'ll need this pattern again in other evaluation sections today, so\nwe put it in a reusable helper.\n\nIt contains helper functions we\'ll reuse in this module:\n\n- `llm_structured`: calls the OpenAI API with structured output\n- `llm_structured_retry`: retries structured-output calls when a\n  request fails\n- `calc_price`: calculates the price from token usage\n- `calc_total_price`: calculates the total price from multiple usage\n  objects\n- `map_progress`: runs work in parallel and tracks progress. We\'ll use it\n  in the next lesson.\n\nImport the structured-output helper:\n\n```python\nfrom evaluation_utils import llm_structured\n```\n\nUse it on the same document:\n\n```python\nresult, usage = llm_structured(\n    openai_client,\n    data_gen_instructions,\n    user_prompt,\n    Questions\n)\n\nprint(result.questions)\n```\n\n## Tracking cost\n\nThe response also contains token usage:\n\n```python\nusage.input_tokens, usage.output_tokens\n```\n\nAs in the agents module, we calculate the price from `response.usage`.\n\nImport the price helper:\n\n```python\nfrom evaluation_utils import calc_price\n```\n\nCalculate the cost of this call:\n\n```python\ncost = calc_price(usage)\n\ncost\n```\n\nNow convert these questions into ground truth records:\n\n```python\nrecords = []\n\nfor q in result.questions:\n    records.append({\n        "question": q,\n        "document": doc["id"]\n    })\n\nrecords\n```\n\nEach record has two fields:\n\n- `question`: the question generated by the LLM\n- `document`: the ID of the FAQ document that should answer the question\n\nThe `document` field connects the generated question to the document\nthat contains the answer. Later, when we evaluate search, we\'ll ask the\nsearch engine the generated question. Then we\'ll check if it retrieves\nthe document with this ID.\n\nWe now know how to generate and store questions for one document. In\nthe next lesson, we\'ll run this for all LLM Zoomcamp FAQ documents and\nsave the full ground truth dataset.\n\n[← Evaluation](01-intr',
  'filename': '04-evaluation/lessons/02-ground-truth.md'},
 {'start': 4000,
  'content': "hat the LLM generates.\nThat search step is what gives the LLM the context it needs to answer\ncorrectly.\n\nWhat we just did was naive. I knew in advance which FAQ entry held the\nanswer and pasted it in by hand. What we want instead is to perform\nsearch automatically. We take the student's question, find the most\nrelevant documents, and send those to the LLM.\n\nIn code, it looks like this:\n\n```python\ndef rag(question):\n    search_results = search(question)\n    user_prompt = build_prompt(question, search_results)\n    return llm(user_prompt)\n```\n\nThat's the entire architecture. It comes down to three components.\n\nThe pieces are search, the prompt, and the LLM:\n\n- search\n- prompt\n- LLM\n\n\n```mermaid\nflowchart TD\n    U([User])\n\n    APP[Application]\n\n    DB[(DB)]\n    DOCS[[D1 ... D5]]\n\n    PROMPT[Build Prompt<br/>Question + Context]\n\n    LLM[LLM]\n\n    ANSWER([Answer])\n\n    U -->|Question| APP\n\n    APP -->|Query| DB\n    DB -->|Retrieved Data| DOCS\n    DOCS --> APP\n\n    APP --> PROMPT\n    PROMPT --> LLM\n\n    LLM --> ANSWER\n    ANSWER --> U\n```\n\nThe LLM only sees the documents we hand it, so its answers are grounded\nin our data. If the right document is retrieved, the answer is good. If\nit's not, the LLM gets the wrong context and the answer is wrong. Your\nmodel is only as good as your retrieval, so search quality matters a\nlot for RAG.\n\nThe database and the LLM can be anything. In this course we use\nminsearch and then sqlitesearch for search, and OpenAI for the LLM. But\nyou can swap any component for another and see what works better.\n\nBecause each piece is independent, RAG stays flexible. To use Anthropic\ninstead of OpenAI, you swap the LLM call. To use Elasticsearch instead\nof minsearch, you swap the search call. Nothing else changes.\n\nIn the next section, we'll look at the dataset we'll use for our FAQ\nknowledge base.\n\n[← Environment](02-environment.md) | [The Course FAQ Dataset →](04-dataset.md)",
  'filename': '01-agentic-rag/lessons/03-rag.md'},
 {'start': 9000,
  'content': ' the user question as possible when making first requests.\n\nMake multiple searches. First perform search, analyze the results \nand then perform more searches. \n\nThe question has to be about the course or its logistics, offtopic questions \nshouldn\'t be answered. If the search returns nothing, it\'s likely an off-topic question.\nIf you can\'t answer the question using FAQ, don\'t do it yourself. Only use the \nfacts from the FAQ database.\n\nAt the end, ask if there are other areas that the user wants to explore.\n""".strip()\n\nagent_loop(instructions, "what\'s queen gambit?")\n```\n\nThis is a lightweight form of an input guardrail. We tell the agent\nwhat\'s in scope and what isn\'t. A real guardrail checks the input\nbefore the agent runs and can block off-topic questions outright.\nThat\'s a separate topic, but instructions are the first place to start.\n\nThis handwritten loop is the best way to understand what frameworks\nhide from you. Every agent framework wraps this same pattern, whether\nit\'s LangChain, PydanticAI, or the OpenAI Agents SDK.\n\n[← Function Calling](13-function-calling.md) | [ToyAIKit →](15-frameworks.md)',
  'filename': '01-agentic-rag/lessons/14-agentic-loop.md'}]

In [24]:

# Build a vector index (VectorSearch), keyed on filename. Wrap in a function, that takes a query and the number of results to return (5 by default).

from embedder import Embedder
embed = Embedder() 

# embed lesson contents from chunks
contents = [
    chunk['content'] for chunk in chunks
]
vectors = embed.encode_batch(
    contents
)
import numpy as np
X = np.array(vectors)

from minsearch import VectorSearch
vindex = VectorSearch(keyword_fields=["filename"])
vindex.fit(X, chunks)


def vector_search(query, num_results=5):

    # embed query 
    v = embed.encode(query)

    return vindex.search(v)[:num_results]  # could be optimized with num_results keyword

example_vector_search = vector_search("What wheather is today?")
example_vector_search

[{'start': 4000,
  'content': 'relevance_total_text\n```\n\nFor the data we prepared on May 29, 2026, this gives:\n\n```python\n[\n    [1, 0, 0, 0, 0],\n    [0, 1, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [0, 0, 0, 0, 0],\n    [0, 1, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [0, 0, 1, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n]\n```\n\nEach entry in `relevance_total_text` is a relevance list. This is\nenough to check that the function works before we run it for the full\ndataset.\n\nNext, make the relevance functions generic. We start with text search,\nbut later we may want to evaluate vector search, hybrid search, or\nanother retrieval method. The relevance logic is the same. Only the\nsearch function changes.\n\n```python\ndef compute_relevance(q, search_function):\n    doc_id = q["document"]\n    results = search_function(query=q["question"])\n\n    relevance = []\n    for d in results:\n        relevance.append(int(d["id"] == doc_id))\n\n    return relevance\n```\n\nThe total relevance function gets a `search_function` too.\n\nWe need to provide it explicitly:\n\n```python\ndef compute_relevance_total(ground_truth, search_function):\n    relevance_total = []\n\n    for q in tqdm(ground_truth):\n        relevance = compute_relevance(q, search_function)\n        relevance_total.append(relevance)\n\n    return relevance_total\n```\n\nUse it with `text_search` on the same sample:\n\n```python\nrelevance_total = compute_relevance_total(ground_truth_sample, text_search)\nrelevance_total\n```\n\nNow run it for all ground truth questions:\n\n```python\nrelevance_total = compute_relevance_total(ground_truth, text_search)\n```\n\nNow we can represent search results as relevance lists. In the next\nlesson, we\'ll turn these lists into metrics: Hit Rate and MRR.\n\n[← Generating Ground Truth for All Documents](03-ground-truth-batch.md) | [Search Evaluation Metrics →](05-search-metrics.md)',
  'filename': '04-evaluation/lessons/04-search-evaluation.md'},
 {'start': 3000,
  'content': 'futures, ask ChatGPT to walk\nthrough this helper line by line.\n\nThen replace the loop with the parallel version:\n\n```python\nwith ThreadPoolExecutor(max_workers=6) as pool:\n    results = map_progress(pool, documents, generate_ground_truth)\n```\n\n`generate_ground_truth` returns two things for each document: the\ngenerated records and the token usage.\n\nSplit those into separate lists:\n\n```python\nground_truth = []\nusages = []\n\nfor records, usage in results:\n    ground_truth.extend(records)\n    usages.append(usage)\n\nlen(ground_truth)\n```\n\nWith 5 questions per document, you should get roughly 5x the number of\ndocuments.\n\n\nCalculate the total cost:\n\n```python\nfrom evaluation_utils import calc_price\n\ntotal_cost = 0.0\n\nfor usage in usages:\n    cost = calc_price(usage)\n    total_cost = total_cost + cost["total_cost"]\n\ntotal_cost\n```\n\nWe\'ll calculate total cost several times in this module, so the utility\nfile has a helper for it:\n\n```python\nfrom evaluation_utils import calc_total_price\n\ncalc_total_price(usages)\n```\n\nCreate a dataframe so we can look at the records as a table and save\nthem as a CSV file.\n\nCreate the dataframe:\n\n```python\nimport pandas as pd\n\ndf_ground_truth = pd.DataFrame(ground_truth)\n```\n\nBecause we generated the questions from specific documents, we know\nwhich document is correct for each question. We now have the ground\ntruth we need for evaluation.\n\nSave it for later use:\n\n```python\ndf_ground_truth.to_csv("data/ground_truth-new.csv", index=False)\n```\n\nWe generated this file for the course materials on May 29, 2026. The\nrun used 79 LLM Zoomcamp documents and produced 395 questions.\n\nThe FAQ data can change over time. If you run the notebook later, you\nmay see different documents and generated questions. Token usage, cost,\nand search evaluation results may also change.\n\nThe total cost was $0.057187, about 6 cents.\n\nIf you don\'t want to generate the questions yourself, download the file\nwe prepared:\n\n```bash\nPREFIX=https://raw.githubusercontent.com/DataTalksCl',
  'filename': '04-evaluation/lessons/03-ground-truth-batch.md'},
 {'start': 3000,
  'content': 'ocument was the first search result.\n\nHere are two more examples from the generated ground truth data.\n\nFor this question:\n\n```python\nq = ground_truth[11]\nprint(q["question"])\ncompute_relevance_text(q)\n# [1, 0, 0, 0, 0]\n```\n\nHere, the correct document was also the first search result.\n\nFor this question:\n\n```python\nq = ground_truth[50]\nprint(q["question"])\ncompute_relevance_text(q)\n# [1, 0, 0, 0, 0]\n```\n\nThe correct document was found at the first position again.\n\nNow do the same thing for all ground truth questions:\n\n```python\nfrom tqdm.auto import tqdm\n\ndef compute_relevance_total_text(ground_truth):\n    relevance_total = []\n\n    for q in tqdm(ground_truth):\n        relevance = compute_relevance_text(q)\n        relevance_total.append(relevance)\n\n    return relevance_total\n```\n\nCall it for the first 15 ground truth questions:\n\n```python\nground_truth_sample = ground_truth[:15]\nrelevance_total_text = compute_relevance_total_text(ground_truth_sample)\n```\n\nLook at the results:\n\n```python\nrelevance_total_text\n```\n\nFor the data we prepared on May 29, 2026, this gives:\n\n```python\n[\n    [1, 0, 0, 0, 0],\n    [0, 1, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [0, 0, 0, 0, 0],\n    [0, 1, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [0, 0, 1, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n    [1, 0, 0, 0, 0],\n]\n```\n\nEach entry in `relevance_total_text` is a relevance list. This is\nenough to check that the function works before we run it for the full\ndataset.\n\nNext, make the relevance functions generic. We start with text search,\nbut later we may want to evaluate vector search, hybrid search, or\nanother retrieval method. The relevance logic is the same. Only the\nsearch function changes.\n\n```python\ndef compute_relevance(q, search_function):\n    doc_id = q["document"]\n    results = search_function(query=q["question"])\n\n    relevance = []\n    for d in results:\n        relevance.append(int(d["id',
  'filename': '04-evaluation/lessons/04-search-evaluation.md'},
 {'start': 4000,
  'content': 'ogress\n```\n\nRun RAG for all ground truth questions:\n\n```python\nwith ThreadPoolExecutor(max_workers=6) as pool:\n    results = map_progress(pool, ground_truth, generate_rag_answer)\n```\n\n`generate_rag_answer` returns one answer record for each question.\n\nCollect the answer records:\n\n```python\nanswers = []\n\nfor answer_record in results:\n    answers.append(answer_record)\n```\n\nCalculate the total cost:\n\n```python\nassistant.total_cost()\n```\n\nSave the answers:\n\n```python\ndf_answers = pd.DataFrame(answers)\ndf_answers.to_csv("data/rag-answers-new.csv", index=False)\n```\n\nWe generated this file for the course materials on May 29, 2026. The\nrun used 395 ground truth questions.\n\nThe total cost was $0.34332825, about 34 cents.\n\nIf you don\'t want to generate the RAG answers yourself, download the\nfile we prepared:\n\n```bash\nPREFIX=https://raw.githubusercontent.com/DataTalksClub/llm-zoomcamp/main\n\nwget -O data/rag-answers-new.csv ${PREFIX}/04-evaluation/data/rag-answers-new.csv\n```\n\nIn the next lesson, we\'ll evaluate these answers with an LLM judge.\n\n[← RAG and Agent Evaluation](11-evaluation-intro.md) | [LLM as a Judge →](13-llm-as-judge.md)',
  'filename': '04-evaluation/lessons/12-rag-answers.md'},
 {'start': 3000,
  'content': 'be accurate.\n\n### Step 2: With RAG\n\nFlow: [`2_chat_with_rag.yaml`](../flows/2_chat_with_rag.yaml)\n\nThis flow:\n\n1. Ingests the Kestra 1.1 release blog post from GitHub\n2. Creates embeddings using Gemini\'s embedding model\n3. Stores embeddings in Kestra\'s KV Store\n4. Asks the LLM the same question with RAG enabled\n5. Returns an accurate response with real features from that release\n\nImport and run `2_chat_with_rag.yaml` and compare the output quality against the previous flow.\n\n## Extending RAG with web search\n\nThe examples above use static RAG — documents are ingested once and stored in the KV Store. Kestra also supports web search as a retriever, which fetches live results at query time and passes them as context to the LLM.\n\nFlow: [`3_rag_with_websearch.yaml`](../flows/3_rag_with_websearch.yaml)\n\n> Note: This flow uses OpenAI as its AI provider. To run it, you\'ll need an OpenAI API key:\n>\n> 1. Visit [platform.openai.com](https://platform.openai.com/home) and sign in or create an account\n> 2. Go to API keys and create a new key\n> 3. Export it as a secret before starting Kestra:\n>    ```bash\n>    export SECRET_OPENAI_API_KEY=$(echo -n "your-openai-api-key-here" | base64)\n>    docker compose up -d\n>    ```\n> 4. Reference it in flows with `{{ secret(\'OPENAI_API_KEY\') }}`\n>\n> If you\'d prefer to keep using Gemini, swap the `provider` block for `io.kestra.plugin.ai.provider.GoogleGemini` with your Gemini API key. See the [full list of supported providers](https://kestra.io/plugins/plugin-ai/provider).\n\nThe `TavilyWebSearch` retriever queries [Tavily](https://www.tavily.com/) and injects the results as context before the LLM generates a response — no ingestion step required. However, the results are only as good as the search engine, and may not be relevant or accurate. Always test the quality of retrieved context when using web search RAG.\n\n### Static RAG vs. web search RAG\n\n| | Static RAG | Web Search RAG |\n|---|---|---|\n| Data source | Documents you ingested | Live web r',
  'filename': '03-orchestration/lessons/05-rag.md'}]

In [25]:
# For hybrid search, reuse the rrf function from homework 2:

def rrf(result_lists, k=60, num_results=5):
    scores = {}
    docs = {}

    for results in result_lists:
        for rank, doc in enumerate(results):
            key = (doc["filename"], doc["start"])
            scores[key] = scores.get(key, 0) + 1 / (k + rank)
            docs[key] = doc

    ranked = sorted(scores, key=scores.get, reverse=True)
    return [docs[key] for key in ranked[:num_results]]

# Then define hybrid_search on top of it:

def hybrid_search(query, k=60):
    text_results = text_search(query, num_results=10)
    vector_results = vector_search(query, num_results=10)
    return rrf([text_results, vector_results], k=k)

example_hybrid_search = hybrid_search("What weather is today?")
example_hybrid_search

[{'start': 4000,
  'content': '\nCall the LLM for one document:\n\n```python\nfrom dotenv import load_dotenv\nfrom openai import OpenAI\n\nload_dotenv()\nopenai_client = OpenAI()\n```\n\nPrepare the document as JSON:\n\n```python\nimport json\n\nuser_prompt = json.dumps(doc)\n```\n\nCreate the messages:\n\n```python\nmessages = [\n    {"role": "developer", "content": data_gen_instructions},\n    {"role": "user", "content": user_prompt}\n]\n```\n\nUntil now we called `responses.create` and read `response.output_text`.\nFor structured output we switch to `responses.parse` and pass\n`text_format=Questions`, which tells the API to return our class instead\nof free text.\n\nCall the model:\n\n```python\nresponse = openai_client.responses.parse(\n    model="gpt-5.4-mini",\n    input=messages,\n    text_format=Questions\n)\n```\n\nThe parsed object is available in `response.output_parsed`:\n\n```python\nresult = response.output_parsed\n\nprint(result)\n```\n\nWe can access the list directly:\n\n```python\nprint(result.questions)\n```\n\nYou should see 5 questions that relate to the first FAQ document.\n\n## Reusable utilities\n\nWe\'ll need this pattern again in other evaluation sections today, so\nwe put it in a reusable helper.\n\nIt contains helper functions we\'ll reuse in this module:\n\n- `llm_structured`: calls the OpenAI API with structured output\n- `llm_structured_retry`: retries structured-output calls when a\n  request fails\n- `calc_price`: calculates the price from token usage\n- `calc_total_price`: calculates the total price from multiple usage\n  objects\n- `map_progress`: runs work in parallel and tracks progress. We\'ll use it\n  in the next lesson.\n\nImport the structured-output helper:\n\n```python\nfrom evaluation_utils import llm_structured\n```\n\nUse it on the same document:\n\n```python\nresult, usage = llm_structured(\n    openai_client,\n    data_gen_instructions,\n    user_prompt,\n    Questions\n)\n\nprint(result.questions)\n```\n\n## Tracking cost\n\nThe response also contains token usage:\n\n```python\nusage.input_tokens, usage.output_tokens\n```\n\nAs in the agents module, ',
  'filename': '04-evaluation/lessons/02-ground-truth.md'},
 {'start': 1000,
  'content': '5432 \\\n    -v pgdata:/var/lib/postgresql/data \\\n    postgres:17\n```\n\nIf the commands feel opaque, paste them into ChatGPT and ask it to walk\nyou through each flag. The first module of our\n[data-engineering-zoomcamp](https://github.com/DataTalksClub/data-engineering-zoomcamp)\ngoes deeper into Docker if you want the longer version.\n\nThese are long commands we\'ll run again and again, so they go in the\n`Makefile` from lesson 02. The `postgres` target depends on `network`,\nso `make postgres` creates the network first and then starts the\ncontainer.\n\nAdd these targets:\n\n```makefile\nnetwork:\n\tdocker network create monitoring\n\npostgres: network\n\tdocker run -it \\\n\t\t--name course-assistant-pg \\\n\t\t--network monitoring \\\n\t\t-e POSTGRES_USER=user \\\n\t\t-e POSTGRES_PASSWORD=password \\\n\t\t-e POSTGRES_DB=course_assistant \\\n\t\t-p 5432:5432 \\\n\t\t-v pgdata:/var/lib/postgresql/data \\\n\t\tpostgres:17\n```\n\nNow we can just run:\n\n```bash\nmake postgres\n```\n\n\nTo reach Postgres from Python, we install the `psycopg` driver:\n\n```bash\nuv add "psycopg[binary]"\n```\n\n## Initializing the database\n\nThe table stores everything from our `LLMCallRecord`, plus the question\nand the course. I call it `conversations`, which isn\'t the best name. I\ncarried it over from materials I recorded a couple of years ago.\nSomething like `llm_call_records` would describe it better, but the name\nstuck. Name yours however you like.\n\nTwo fields are worth a word. We store the `course` because the same\nassistant can serve more than one course. Right now everything is\n`llm-zoomcamp`, but keeping the column means we don\'t have to reshape the\ntable when we add others. The `timestamp` is timezone-aware\n(`TIMESTAMP WITH TIME ZONE`) on purpose. Without the time zone, Grafana\nwon\'t line the data up correctly on its time axis later.\n\nThe SQL to create the table:\n\n```sql\nCREATE TABLE conversations (\n    id SERIAL PRIMARY KEY,\n    question TEXT NOT NULL,\n    answer TEXT NOT NULL,\n    course TEXT NOT NULL,\n    model TEXT NOT NULL,\n    instructi',
  'filename': '05-monitoring/lessons/05-database.md'},
 {'start': 3000,
  'content': 'we drop it.\n\nBuild a prompt that includes both the question and the context:\n\n```python\nprompt = f"""\nYour task is to answer questions from the course participants\nbased on the provided context.\n\nUse the context to find relevant information and provide accurate\nanswers. If the answer is not found in the context,\nrespond with "I don\'t know."\n\nQuestion:\n{question}\n\nContext:\n{context}\n"""\n```\n\nInstead of sending the raw question to the LLM, we send this prompt:\n\n```python\nanswer = llm(prompt)\nprint(answer)\n```\n\nAfter that, the answer is correct: "Yes, you can still join. If you want to\nreceive a certificate, you need to submit your project while\nsubmissions are still open."\n\nThis is the answer we actually want to give to our students. What we\njust did is nothing but RAG.\n\n## Retrieval plus generation\n\nRAG stands for Retrieval-Augmented Generation. Generation is the LLM\nproducing text, and retrieval is search. We retrieve relevant documents\nfrom our knowledge base and use them to augment what the LLM generates.\nThat search step is what gives the LLM the context it needs to answer\ncorrectly.\n\nWhat we just did was naive. I knew in advance which FAQ entry held the\nanswer and pasted it in by hand. What we want instead is to perform\nsearch automatically. We take the student\'s question, find the most\nrelevant documents, and send those to the LLM.\n\nIn code, it looks like this:\n\n```python\ndef rag(question):\n    search_results = search(question)\n    user_prompt = build_prompt(question, search_results)\n    return llm(user_prompt)\n```\n\nThat\'s the entire architecture. It comes down to three components.\n\nThe pieces are search, the prompt, and the LLM:\n\n- search\n- prompt\n- LLM\n\n\n```mermaid\nflowchart TD\n    U([User])\n\n    APP[Application]\n\n    DB[(DB)]\n    DOCS[[D1 ... D5]]\n\n    PROMPT[Build Prompt<br/>Question + Context]\n\n    LLM[LLM]\n\n    ANSWER([Answer])\n\n    U -->|Question| APP\n\n    APP -->|Query| DB\n    DB -->|Retrieved Data| DOCS\n    DOCS --> APP\n\n    APP --> PROMPT\n    PROMPT -',
  'filename': '01-agentic-rag/lessons/03-rag.md'},
 {'start': 1000,
  'content': ': question_boost, "section": 0.5}\n\n    return index.search(\n        query,\n        num_results=5,\n        boost_dict=boost_dict,\n    )\n```\n\nEvaluate several boost values:\n\n```python\nfor boost in [0.5, 1.0, 3.0, 5.0, 10.0]:\n    result = evaluate(\n        ground_truth,\n        lambda query, boost=boost: search_boost(query, boost)\n    )\n    print(f"boost={boost}: {result}")\n```\n\nFor the data we prepared on May 29, 2026, this gives:\n\n```python\nboost=0.5: {\'hit_rate\': 0.9113924050632911, \'mrr\': 0.800548523206751}\nboost=1.0: {\'hit_rate\': 0.9240506329113924, \'mrr\': 0.8139240506329113}\nboost=3.0: {\'hit_rate\': 0.8987341772151899, \'mrr\': 0.7693248945147676}\nboost=5.0: {\'hit_rate\': 0.8708860759493671, \'mrr\': 0.7401265822784809}\nboost=10.0: {\'hit_rate\': 0.8582278481012658, \'mrr\': 0.7122362869198313}\n```\n\nIncreasing the question boost makes the metrics worse, not better. The\nbest value here is `1.0`, no boost at all. That\'s already the opposite of\nwhat the intuition predicted.\n\nBut this is only one parameter. We can also tune `answer` and `section`\ntogether with `question`.\n\nDefine a search function with all three boosts:\n\n```python\ndef search_boosts(query, question_boost, answer_boost, section_boost):\n    boost_dict = {\n        "question": question_boost,\n        "section": section_boost,\n        "answer": answer_boost,\n    }\n\n    return index.search(\n        query,\n        num_results=5,\n        boost_dict=boost_dict,\n    )\n```\n\nNow do a small grid search:\n\n```python\nresults = []\n\nfor question_boost in [1.0, 2.0, 5.0]:\n    for answer_boost in [1.0, 2.0, 4.0, 10.0]:\n        for section_boost in [0.1, 0.2, 0.5]:\n            print(\n                f"Evaluating question_boost={question_boost},"\n                f" answer_boost={answer_boost},"\n                f" section_boost={section_boost}..."\n            )\n            result = evaluate(\n                ground_truth,\n                lambda query, question_boost=question_boost, answer_boost=answer_boost, section_boost=section_boos',
  'filename': '04-evaluation/lessons/06-search-tuning.md'},
 {'start': 5000,
  'content': 'the first FAQ document.\n\n## Reusable utilities\n\nWe\'ll need this pattern again in other evaluation sections today, so\nwe put it in a reusable helper.\n\nIt contains helper functions we\'ll reuse in this module:\n\n- `llm_structured`: calls the OpenAI API with structured output\n- `llm_structured_retry`: retries structured-output calls when a\n  request fails\n- `calc_price`: calculates the price from token usage\n- `calc_total_price`: calculates the total price from multiple usage\n  objects\n- `map_progress`: runs work in parallel and tracks progress. We\'ll use it\n  in the next lesson.\n\nImport the structured-output helper:\n\n```python\nfrom evaluation_utils import llm_structured\n```\n\nUse it on the same document:\n\n```python\nresult, usage = llm_structured(\n    openai_client,\n    data_gen_instructions,\n    user_prompt,\n    Questions\n)\n\nprint(result.questions)\n```\n\n## Tracking cost\n\nThe response also contains token usage:\n\n```python\nusage.input_tokens, usage.output_tokens\n```\n\nAs in the agents module, we calculate the price from `response.usage`.\n\nImport the price helper:\n\n```python\nfrom evaluation_utils import calc_price\n```\n\nCalculate the cost of this call:\n\n```python\ncost = calc_price(usage)\n\ncost\n```\n\nNow convert these questions into ground truth records:\n\n```python\nrecords = []\n\nfor q in result.questions:\n    records.append({\n        "question": q,\n        "document": doc["id"]\n    })\n\nrecords\n```\n\nEach record has two fields:\n\n- `question`: the question generated by the LLM\n- `document`: the ID of the FAQ document that should answer the question\n\nThe `document` field connects the generated question to the document\nthat contains the answer. Later, when we evaluate search, we\'ll ask the\nsearch engine the generated question. Then we\'ll check if it retrieves\nthe document with this ID.\n\nWe now know how to generate and store questions for one document. In\nthe next lesson, we\'ll run this for all LLM Zoomcamp FAQ documents and\nsave the full ground truth dataset.\n\n[← Evaluation](01-intr',
  'filename': '04-evaluation/lessons/02-ground-truth.md'}]

In [26]:
"""
Q2. First result with text search
Take the first question from the ground truth:

q = ground_truth[0]["question"]
After running text_search for it, what's the filename of the first result?

01-agentic-rag/lessons/01-intro.md
01-agentic-rag/lessons/03-rag.md
01-agentic-rag/lessons/13-function-calling.md
01-agentic-rag/lessons/10-rag-next-steps.md
"""

q = ground_truth[0]["question"]
print(q)
text_search(q)

# SOLUTION: filename': '01-agentic-rag/lessons/03-rag.md

What exactly is a retrieval-augmented generation system, and why does it help with answers that the model wouldn't know on its own?

[{'start': 3000,
  'content': 'we drop it.\n\nBuild a prompt that includes both the question and the context:\n\n```python\nprompt = f"""\nYour task is to answer questions from the course participants\nbased on the provided context.\n\nUse the context to find relevant information and provide accurate\nanswers. If the answer is not found in the context,\nrespond with "I don\'t know."\n\nQuestion:\n{question}\n\nContext:\n{context}\n"""\n```\n\nInstead of sending the raw question to the LLM, we send this prompt:\n\n```python\nanswer = llm(prompt)\nprint(answer)\n```\n\nAfter that, the answer is correct: "Yes, you can still join. If you want to\nreceive a certificate, you need to submit your project while\nsubmissions are still open."\n\nThis is the answer we actually want to give to our students. What we\njust did is nothing but RAG.\n\n## Retrieval plus generation\n\nRAG stands for Retrieval-Augmented Generation. Generation is the LLM\nproducing text, and retrieval is search. We retrieve relevant documents\nfrom our knowledge base and use them to augment what the LLM generates.\nThat search step is what gives the LLM the context it needs to answer\ncorrectly.\n\nWhat we just did was naive. I knew in advance which FAQ entry held the\nanswer and pasted it in by hand. What we want instead is to perform\nsearch automatically. We take the student\'s question, find the most\nrelevant documents, and send those to the LLM.\n\nIn code, it looks like this:\n\n```python\ndef rag(question):\n    search_results = search(question)\n    user_prompt = build_prompt(question, search_results)\n    return llm(user_prompt)\n```\n\nThat\'s the entire architecture. It comes down to three components.\n\nThe pieces are search, the prompt, and the LLM:\n\n- search\n- prompt\n- LLM\n\n\n```mermaid\nflowchart TD\n    U([User])\n\n    APP[Application]\n\n    DB[(DB)]\n    DOCS[[D1 ... D5]]\n\n    PROMPT[Build Prompt<br/>Question + Context]\n\n    LLM[LLM]\n\n    ANSWER([Answer])\n\n    U -->|Question| APP\n\n    APP -->|Query| DB\n    DB -->|Retrieved Data| DOCS\n    DOCS --> APP\n\n    APP --> PROMPT\n    PROMPT -',
  'filename': '01-agentic-rag/lessons/03-rag.md'},
 {'start': 1000,
  'content': 'decides when to call it and what to search for.\n\nThe same typo question now goes like this:\n\n```mermaid\nflowchart TD\n    U([User: How do I run Olama?])\n    L1[LLM: I\'ll search for \'Olama\']\n    S1[search - Olama - no useful results]\n    L2[LLM: Hmm, no results. Maybe a typo for \'Ollama\'?]\n    S2[search - Ollama - found results!]\n    A([LLM: Here\'s how to run Ollama locally...])\n\n    U --> L1 --> S1 --> L2 --> S2 --> A\n```\n\nThe LLM searched, saw the results were bad, and decided to try again\nwith a different query. It made that decision on its own. We didn\'t\nwrite any code to handle typos.\n\nThe difference is about who makes the decisions:\n\n- With RAG, the developer decides. We fix the steps up front, so\n  search always runs once with the exact user query.\n- With an agent, the LLM decides. It chooses which actions to take\n  and when to stop.\n\nThe mechanism that makes this possible is function calling, and that\'s\nwhat the rest of this lesson is about.\n\n## Asking without tools\n\nFirst, let\'s see what the LLM does without any tools. We ask it a\ncourse-specific question and look at the answer.\n\n```python\nmessages = [\n    {"role": "user", "content": "I just discovered the course. Can I join it?"}\n]\n\nresponse = openai_client.responses.create(\n    model="gpt-5.4-mini",\n    input=messages,\n)\n\nresponse.output_text\n```\n\nThe model answers from its general knowledge, something like "it\ndepends on the course" or "check the course website". It doesn\'t know\nabout our FAQ, so the answer is vague and not helpful. This is exactly\nwhy we need RAG, and why we want to hand the model a tool.\n\n## Defining the tool\n\nFirst we define a top-level `search` function that queries the `index`\ndirectly. The model will reference it by this name. We keep the Python\nfunction and the tool name aligned so the dispatch is easier later.\n\n```python\ndef search(query):\n    boost_dict = {"question": 3.0, "section": 0.5}\n    filter_dict = {"course": "llm-zoomcamp"}\n\n    return index.search(\n        query,\n       ',
  'filename': '01-agentic-rag/lessons/13-function-calling.md'},
 {'start': 2000,
  'content': 'you want to receive a certificate, you need to submit your project while we\'re still accepting submissions.\n\nCourse: I have registered for the LLM Zoomcamp. When can I expect to receive the confirmation email?\nYou don\'t need it. You\'re accepted. You can also just start learning and submitting homework (while the form is open) without registering. It is not checked against any registered list. Registration is just to gauge interest before the start date.\n\nWhat is the video/zoom link to the stream for the "Office Hours" or live/workshop sessions?\nThe zoom link is only published to instructors/presenters/TAs. Students participate via YouTube Live and submit questions to Slido.\n\nCloud alternatives with GPU\nCheck the quota and reset cycle carefully. Potential options include Google Colab, Kaggle, Databricks.\n"""\n```\n\nNotice the prompt doesn\'t end with `Answer:`. With older models like\nGPT-3 we added that to nudge the model into completing the sentence.\nModern models don\'t need the hint, so we drop it.\n\nBuild a prompt that includes both the question and the context:\n\n```python\nprompt = f"""\nYour task is to answer questions from the course participants\nbased on the provided context.\n\nUse the context to find relevant information and provide accurate\nanswers. If the answer is not found in the context,\nrespond with "I don\'t know."\n\nQuestion:\n{question}\n\nContext:\n{context}\n"""\n```\n\nInstead of sending the raw question to the LLM, we send this prompt:\n\n```python\nanswer = llm(prompt)\nprint(answer)\n```\n\nAfter that, the answer is correct: "Yes, you can still join. If you want to\nreceive a certificate, you need to submit your project while\nsubmissions are still open."\n\nThis is the answer we actually want to give to our students. What we\njust did is nothing but RAG.\n\n## Retrieval plus generation\n\nRAG stands for Retrieval-Augmented Generation. Generation is the LLM\nproducing text, and retrieval is search. We retrieve relevant documents\nfrom our knowledge base and use them to augment w',
  'filename': '01-agentic-rag/lessons/03-rag.md'},
 {'start': 2000,
  'content': ' see what the LLM does without any tools. We ask it a\ncourse-specific question and look at the answer.\n\n```python\nmessages = [\n    {"role": "user", "content": "I just discovered the course. Can I join it?"}\n]\n\nresponse = openai_client.responses.create(\n    model="gpt-5.4-mini",\n    input=messages,\n)\n\nresponse.output_text\n```\n\nThe model answers from its general knowledge, something like "it\ndepends on the course" or "check the course website". It doesn\'t know\nabout our FAQ, so the answer is vague and not helpful. This is exactly\nwhy we need RAG, and why we want to hand the model a tool.\n\n## Defining the tool\n\nFirst we define a top-level `search` function that queries the `index`\ndirectly. The model will reference it by this name. We keep the Python\nfunction and the tool name aligned so the dispatch is easier later.\n\n```python\ndef search(query):\n    boost_dict = {"question": 3.0, "section": 0.5}\n    filter_dict = {"course": "llm-zoomcamp"}\n\n    return index.search(\n        query,\n        num_results=5,\n        boost_dict=boost_dict,\n        filter_dict=filter_dict\n    )\n```\n\nNext we tell the model about this function. The model doesn\'t see our\nPython code, only a schema describing what the function does and what\narguments it takes. LLMs are language agnostic. At the end we\'re just\nmaking an HTTP call, so we describe the tool in JSON rather than in\nPython. The same schema would work from TypeScript or Java.\n\n```python\nsearch_tool = {\n    "type": "function",\n    "name": "search",\n    "description": "Search the FAQ database for entries matching the given query.",\n    "parameters": {\n        "type": "object",\n        "properties": {\n            "query": {\n                "type": "string",\n                "description": "Search query text to look up in the course FAQ."\n            }\n        },\n        "required": ["query"],\n        "additionalProperties": False\n    }\n}\n```\n\nThe `description` is the most important field, because the model reads\nit to decide when to call the',
  'filename': '01-agentic-rag/lessons/13-function-calling.md'},
 {'start': 0,
  'content': '# Introduction\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=rQYyFxf1FWw&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn this module, we\'ll build a working Retrieval-Augmented\nGeneration (RAG) system from scratch, step by step.\n\nWe write everything in plain Python. We build a small search index by\nhand and call the LLM ourselves. I want you to see every piece first.\nThat way you know what a framework does for you before you reach for\none.\n\nPlaces where you can find me:\n\n- [My substack](https://alexeyondata.substack.com/)\n- [LinkedIn](https://www.linkedin.com/in/agrigorev/)\n- [X](https://x.com/Al_Grigor)\n\n## LLMs\n\nAn LLM (Large Language Model) is a neural network trained on massive\namounts of text. Given a prompt, it generates a continuation - a\nplausible next piece of text.\n\nThink of your phone. When you type "how are" in WhatsApp, it suggests\n"you" as the next word. "How are you" is the most common continuation.\nYour phone uses a simple language model for that. It predicts the next\nword based on what you typed so far.\n\nA large language model does the same thing, but at a much larger scale.\nIt has billions of parameters and is trained on most of the text on the\ninternet. When it predicts the next word, it feels like you\'re talking\nto an intelligent being. It understands what you ask and gives\nmeaningful answers.\n\nIn this course, we treat LLMs as black boxes. We won\'t look inside or\ncover the theory, and we won\'t host a model ourselves. We use an LLM\nprovider and call it over an API. For us, an LLM is a box: text goes in,\ntext comes out.\n\nBut LLMs have limitations:\n\n- Knowledge cutoff: they only know what was in their training data.\n  If you ask about something that happened after training, they won\'t\n  know - or worse, they\'ll make something up.\n- No access to your data: they can\'t see your documents, databases,\n  or internal systems unless you provide that information.\n- Hallucinations: they sometimes produce confident-sounding answers\n  that are simply ',
  'filename': '01-agentic-rag/lessons/01-intro.md'}]

In [27]:
"""
Q3. First result with vector search
After running vector_search for the same question, what's the filename of the first result?

01-agentic-rag/lessons/01-intro.md
01-agentic-rag/lessons/03-rag.md
04-evaluation/lessons/11-evaluation-intro.md
04-evaluation/lessons/12-rag-answers.md

This question was generated from 01-agentic-rag/lessons/01-intro.md. Notice that one method finds the right page at the top and the other doesn't. That's exactly why we measure across the whole dataset instead of trusting one query.
"""

q = ground_truth[0]["question"]
print(q)
vector_search(q)

# SOLUTION: 'filename': '01-agentic-rag/lessons/01-intro.md'

What exactly is a retrieval-augmented generation system, and why does it help with answers that the model wouldn't know on its own?

[{'start': 0,
  'content': '# Introduction\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=rQYyFxf1FWw&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn this module, we\'ll build a working Retrieval-Augmented\nGeneration (RAG) system from scratch, step by step.\n\nWe write everything in plain Python. We build a small search index by\nhand and call the LLM ourselves. I want you to see every piece first.\nThat way you know what a framework does for you before you reach for\none.\n\nPlaces where you can find me:\n\n- [My substack](https://alexeyondata.substack.com/)\n- [LinkedIn](https://www.linkedin.com/in/agrigorev/)\n- [X](https://x.com/Al_Grigor)\n\n## LLMs\n\nAn LLM (Large Language Model) is a neural network trained on massive\namounts of text. Given a prompt, it generates a continuation - a\nplausible next piece of text.\n\nThink of your phone. When you type "how are" in WhatsApp, it suggests\n"you" as the next word. "How are you" is the most common continuation.\nYour phone uses a simple language model for that. It predicts the next\nword based on what you typed so far.\n\nA large language model does the same thing, but at a much larger scale.\nIt has billions of parameters and is trained on most of the text on the\ninternet. When it predicts the next word, it feels like you\'re talking\nto an intelligent being. It understands what you ask and gives\nmeaningful answers.\n\nIn this course, we treat LLMs as black boxes. We won\'t look inside or\ncover the theory, and we won\'t host a model ourselves. We use an LLM\nprovider and call it over an API. For us, an LLM is a box: text goes in,\ntext comes out.\n\nBut LLMs have limitations:\n\n- Knowledge cutoff: they only know what was in their training data.\n  If you ask about something that happened after training, they won\'t\n  know - or worse, they\'ll make something up.\n- No access to your data: they can\'t see your documents, databases,\n  or internal systems unless you provide that information.\n- Hallucinations: they sometimes produce confident-sounding answers\n  that are simply ',
  'filename': '01-agentic-rag/lessons/01-intro.md'},
 {'start': 0,
  'content': "# RAG and Agent Evaluation\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=VKHBP0QSCFo&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nSo far, we evaluated retrieval. We checked whether search returns the\ndocument that should answer the question.\n\nThat is only the first step. A complete application still needs to\nproduce a final answer. For RAG, this means checking the generated\nanswer. For agents, it also means looking at the tool calls the model\nmade before producing the answer.\n\nRAG evaluation checks the whole flow together.\n\nThis includes:\n\n- search\n- prompt\n- LLM\n\nIf the final answer is bad, the problem can come from any of these\nsteps. The search might retrieve the wrong document, the prompt might\nomit important context, or the LLM might ignore the context.\n\nIn this part, we'll evaluate:\n\n- RAG answers with an LLM judge\n- Agent answers and tool-call trajectories\n\nWe won't go deep into agent evaluation frameworks here. We'll use the\nagent from module 01, save the final answer, and also save the tool\ncalls. Then we can look at whether the answer is good and whether the\ntrajectory looks reasonable.\n\n## LLM as a judge\n\nFor RAG and agent evaluation, we compare the generated answer with the\noriginal answer. The generated answer won't use the same words as the\noriginal. It's a generative model, so the phrasing will be different\neven when the meaning is the same.\n\nThis is why we use another LLM to do the comparison. We show the judge\nthe question, the original answer, and the generated answer. Then we ask\nit to decide if they are semantically equivalent.\n\nThis approach is called LLM-as-a-judge. The evaluating LLM is the\njudge. It classifies each answer as good or bad and explains its\nreasoning. Asking the judge to explain why it made a decision generally\nproduces better classifications than asking for just the verdict.\n\nNext, we'll start with the RAG case and generate answers for the ground\ntruth questions.\n\n[← Search Parameter Tuning](06-search-tuning.md) | [Ge",
  'filename': '04-evaluation/lessons/11-evaluation-intro.md'},
 {'start': 2000,
  'content': '\n\nIt also uses the search boosts we selected in the search tuning lesson:\n`question=1.0`, `answer=2.0`, and `section=0.1`.\n\n```python\nfrom evaluation_utils import RAGWithUsage\n\nassistant = RAGWithUsage(\n    index=index,\n    llm_client=openai_client,\n)\n```\n\nFor each question, `RAGBase` searches the FAQ, builds a prompt with the\nretrieved context, and asks the LLM to answer. We save the answer so the\nnext lesson can judge it.\n\nRun RAG for one question:\n\n```python\nrec = ground_truth[0]\nquestion = rec["question"]\n\nanswer_llm = assistant.rag(question)\nanswer_llm\n```\n\nCheck the cost of this call:\n\n```python\nassistant.total_cost()\n```\n\nGet the original answer from the document ID:\n\n```python\ndoc_id = rec["document"]\noriginal_doc = doc_idx[doc_id]\nanswer_orig = original_doc["answer"]\n\nanswer_orig\n```\n\nNow save both answers in one record:\n\n```python\nrag_result = {\n    "question": question,\n    "answer_llm": answer_llm,\n    "answer_orig": answer_orig,\n    "document": doc_id,\n}\n\nrag_result\n```\n\n## Processing all questions\n\nCreate a function that processes one ground truth record:\n\n```python\ndef generate_rag_answer(rec):\n    question = rec["question"]\n    doc_id = rec["document"]\n    original_doc = doc_idx[doc_id]\n\n    answer_llm = assistant.rag(question)\n    answer_orig = original_doc["answer"]\n\n    result = {\n        "question": question,\n        "answer_llm": answer_llm,\n        "answer_orig": answer_orig,\n        "document": doc_id,\n    }\n\n    return result\n```\n\nTest it on one record:\n\n```python\nanswer_record = generate_rag_answer(ground_truth[0])\nanswer_record\n```\n\nBefore running the full batch, reset the usage we collected while\ntesting:\n\n```python\nassistant.reset_usage()\n```\n\nThis calls the LLM once per ground truth question, so it can take some\ntime. Let\'s process the questions in parallel and track progress.\n\nImport the parallel processing helper from the same utility file:\n\n```python\nfrom concurrent.futures import ThreadPoolExecutor\nfrom evaluation_utils import map_pr',
  'filename': '04-evaluation/lessons/12-rag-answers.md'},
 {'start': 0,
  'content': "# Wrap-up of Part 1\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=RPXMz5p5fb8&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn Part 1 of this module, we:\n\n- Learned what RAG is and why it matters: retrieve documents, build a\n  prompt, let the LLM generate a grounded answer\n- Built a search engine over a real FAQ dataset using minsearch\n- Created a prompt template that combines the user's question with\n  search results\n- Wired search + prompt + LLM into a working RAG pipeline\n- Split ingestion and query into separate processes with sqlitesearch\n\nYou now have a working RAG system and a clear mental model for how each\npiece fits together. From here, the work is making each piece better.\n\n## Two directions forward\n\n[Part 2 of this module: Agents](11-agents-intro.md). Our pipeline runs\nsearch once with the exact user query, unchanged. If that search\nreturns garbage, the LLM has no way to recover. An agent puts the LLM\nin charge instead. It decides what to search for, how many searches to\nrun, and when to stop.\n\nAn agent also handles questions in another language. It translates the\nquery before searching, then translates the answer back afterward.\n\n[Module 2: Vector Search](../../02-vector-search/). Keyword matches\nare exact. Vector search matches by semantic meaning instead, which\nhelps when the user phrases things differently from the FAQ.\n\n## Elasticsearch\n\nElasticsearch is the industry standard for text search.\n\nIt supports:\n\n- Full-text search with BM25\n- Filtering, aggregations, and faceting\n- Vector search (dense and sparse)\n- Distributed scaling\n- Real-time indexing\n\nIt's heavier than sqlitesearch but handles production workloads at\nscale. If you're building a real RAG system, Elasticsearch (or\nOpenSearch) is a common choice for the search backend.\n\nFor an Elasticsearch tutorial, see the\n[supplementary materials for Module 1](../../cohorts/2025/01-intro/elastic-search.md).\n\n## Fine-tuning vs RAG\n\nInstead of retrieving documents at query time, you could f",
  'filename': '01-agentic-rag/lessons/10-rag-next-steps.md'},
 {'start': 0,
  'content': "# Best Practices for RAG\n\nIn the previous modules we built search engines, agents, evaluation\npipelines, and monitoring dashboards. This module covers techniques\nthat improve retrieval quality - the most critical part of any RAG\nsystem.\n\n## The RAG pipeline\n\nA RAG system has two stages:\n\n- Indexing: documents are parsed, chunked, embedded, and stored in\n  a vector database\n- Retrieval: the user's question is embedded, the database is\n  searched for the closest documents, and those documents are\n  passed to the LLM as context\n\nMost of the improvements we'll discuss focus on the retrieval\nstage, because better retrieval means better answers.\n\n## Five techniques\n\nHere are the five techniques we'll cover:\n\n1. Small-to-big chunk retrieval - use small chunks for indexing\n   but retrieve surrounding context for the LLM\n2. Leveraging document metadata - use titles, topics, dates, and\n   other metadata to filter and boost results\n3. Hybrid search - combine vector search (semantic) with keyword\n   search (lexical) in one query\n4. User query rewriting - use an LLM to reformulate the user's\n   question into a better search query\n5. Document reranking - re-order retrieved documents by relevance\n   after the initial search\n\nIn this module, we'll focus on hybrid search and reranking. These\ntwo techniques give the biggest improvement for the least effort.\n\nSlides: [llm-zoomcamp-best-practicies.pdf](../llm-zoomcamp-best-practicies.pdf)\n\nTo learn more:\n\n- [Survey on RAG techniques](https://arxiv.org/abs/2312.10997)\n\n[← Back to module](../) | [Hybrid Search →](02-hybrid-search.md)",
  'filename': '06-best-practices/lessons/01-intro.md'}]

In [28]:
"""
Evaluation metrics

We evaluate search exactly as in the module, reusing the same functions from the lecture. We change only the label. Our ground truth uses filename, so a result counts as a hit when a returned chunk's filename matches the question's filename, not a document id.

The lesson evaluates whole FAQ records, while this homework evaluates chunks. Adjust the relevance logic to use the fields available on the chunk results and homework ground truth instead of copying the lesson's record-based comparison unchanged.

As a reminder, these functions do the following:

- compute_relevance runs search for a question and returns a list of 0s and 1s
- hit_rate is the fraction of questions where the correct page appears in the results
- mrr (Mean Reciprocal Rank) also rewards finding the page near the top
- evaluate runs a search function over the whole ground truth and returns both metrics
"""

"\nEvaluation metrics\n\nWe evaluate search exactly as in the module, reusing the same functions from the lecture. We change only the label. Our ground truth uses filename, so a result counts as a hit when a returned chunk's filename matches the question's filename, not a document id.\n\nThe lesson evaluates whole FAQ records, while this homework evaluates chunks. Adjust the relevance logic to use the fields available on the chunk results and homework ground truth instead of copying the lesson's record-based comparison unchanged.\n\nAs a reminder, these functions do the following:\n\n- compute_relevance runs search for a question and returns a list of 0s and 1s\n- hit_rate is the fraction of questions where the correct page appears in the results\n- mrr (Mean Reciprocal Rank) also rewards finding the page near the top\n- evaluate runs a search function over the whole ground truth and returns both metrics\n"

In [29]:
chunks[:2]

[{'start': 0,
  'content': '# Introduction\n\nVideo: [Watch this lesson](https://www.youtube.com/watch?v=rQYyFxf1FWw&list=PL3MmuxUbc_hLZFNgSad56pDBKK8KO0XIv)\n\nIn this module, we\'ll build a working Retrieval-Augmented\nGeneration (RAG) system from scratch, step by step.\n\nWe write everything in plain Python. We build a small search index by\nhand and call the LLM ourselves. I want you to see every piece first.\nThat way you know what a framework does for you before you reach for\none.\n\nPlaces where you can find me:\n\n- [My substack](https://alexeyondata.substack.com/)\n- [LinkedIn](https://www.linkedin.com/in/agrigorev/)\n- [X](https://x.com/Al_Grigor)\n\n## LLMs\n\nAn LLM (Large Language Model) is a neural network trained on massive\namounts of text. Given a prompt, it generates a continuation - a\nplausible next piece of text.\n\nThink of your phone. When you type "how are" in WhatsApp, it suggests\n"you" as the next word. "How are you" is the most common continuation.\nYour phone uses a simple language model for that. It predicts the next\nword based on what you typed so far.\n\nA large language model does the same thing, but at a much larger scale.\nIt has billions of parameters and is trained on most of the text on the\ninternet. When it predicts the next word, it feels like you\'re talking\nto an intelligent being. It understands what you ask and gives\nmeaningful answers.\n\nIn this course, we treat LLMs as black boxes. We won\'t look inside or\ncover the theory, and we won\'t host a model ourselves. We use an LLM\nprovider and call it over an API. For us, an LLM is a box: text goes in,\ntext comes out.\n\nBut LLMs have limitations:\n\n- Knowledge cutoff: they only know what was in their training data.\n  If you ask about something that happened after training, they won\'t\n  know - or worse, they\'ll make something up.\n- No access to your data: they can\'t see your documents, databases,\n  or internal systems unless you provide that information.\n- Hallucinations: they sometimes produce confident-sounding answers\n  that are simply ',
  'filename': '01-agentic-rag/lessons/01-intro.md'},
 {'start': 1000,
  'content': 'the next\nword based on what you typed so far.\n\nA large language model does the same thing, but at a much larger scale.\nIt has billions of parameters and is trained on most of the text on the\ninternet. When it predicts the next word, it feels like you\'re talking\nto an intelligent being. It understands what you ask and gives\nmeaningful answers.\n\nIn this course, we treat LLMs as black boxes. We won\'t look inside or\ncover the theory, and we won\'t host a model ourselves. We use an LLM\nprovider and call it over an API. For us, an LLM is a box: text goes in,\ntext comes out.\n\nBut LLMs have limitations:\n\n- Knowledge cutoff: they only know what was in their training data.\n  If you ask about something that happened after training, they won\'t\n  know - or worse, they\'ll make something up.\n- No access to your data: they can\'t see your documents, databases,\n  or internal systems unless you provide that information.\n- Hallucinations: they sometimes produce confident-sounding answers\n  that are simply wrong.\n\n## The project\n\nRAG solves these problems by giving the LLM relevant documents at\nquestion time. We don\'t hope the model memorized the answer. We\nretrieve the right information and hand it to the LLM, and the model\ngenerates a grounded response. This lets us inject knowledge the model\nnever saw during training. That\'s why RAG is still the most common way\npeople use LLMs in the industry.\n\nTo make this concrete, we build a FAQ agent for our course. A student\nasks something like "when does the course start?" and the agent answers\nfrom the FAQ data we prepared.\n\nThis module has two parts.\n\nIn Part 1 (the next 9 lessons) we will:\n\n- Understand what RAG is and how it works\n- Build a search engine over a real FAQ dataset\n- Write a prompt that combines the user\'s question with search results\n- Wire it all together into a working RAG pipeline\n- Split ingestion and query into separate processes\n\nIn Part 2, we make the pipeline agentic. The LLM decides when and\nwhat to search, instead of ',
  'filename': '01-agentic-rag/lessons/01-intro.md'}]

In [30]:
ground_truth[:2]

[{'question': "What exactly is a retrieval-augmented generation system, and why does it help with answers that the model wouldn't know on its own?",
  'filename': '01-agentic-rag/lessons/01-intro.md'},
 {'question': 'Why does this course build the RAG project in plain Python instead of starting with a framework or library?',
  'filename': '01-agentic-rag/lessons/01-intro.md'}]

In [31]:
# RELEVANCE

# generic compute of relevance so we can evaluate vector search, hybrid search, or another retrieval method
# but the relevance logic stays the same 

def compute_relevance(q, search_function):
    doc_id = q["filename"]
    results = search_function(query=q["question"])

    relevance = []
    for d in results:
        relevance.append(int(d["filename"] == doc_id))

    return relevance

# for all questions in the ground truth data 

def compute_relevance_total(ground_truth, search_function):
    relevance_total = []

    for q in tqdm(ground_truth):
        relevance = compute_relevance(q, search_function)
        relevance_total.append(relevance)

    return relevance_total

In [32]:
# HIT RATE 

# putting this in a function

def hit_rate(relevance):
    cnt = 0

    for line in relevance:
        if 1 in line:
            cnt = cnt + 1

    return cnt / len(relevance)

In [41]:
# MRR

def mrr(relevance):
    total_score = 0.0

    for line in relevance:
        for rank in range(len(line)):
            if line[rank] == 1:
                total_score = total_score + 1 / (rank + 1)
                break

    return total_score / len(relevance)

In [34]:
"""
Q4. Evaluating text search
Evaluate text_search on the ground truth data.

What's the Hit Rate?

0.55
0.66
0.76
0.88
"""


# compute relevance 

relevance_total = compute_relevance_total(ground_truth=ground_truth, search_function=text_search)
relevance_total[:5]

# compute hit rate 

hit_rate(relevance_total)

# 0.7583 -> NEAREST SOLUTION: 0.76

  0%|          | 0/360 [00:00<?, ?it/s]

0.7583333333333333

In [35]:
"""
Q5. Evaluating vector search
Now evaluate vector_search - the part we left for the homework, since the module only evaluated keyword search.

What's the MRR?

0.35
0.45
0.55
0.65
"""

# compute relevance 

relevance_total = compute_relevance_total(ground_truth=ground_truth, search_function=vector_search)
print(relevance_total[:5])

  0%|          | 0/360 [00:00<?, ?it/s]

[[1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [ ]:
# compute MRR 

mrr = mrr(relevance_total)
print(mrr)

# 0.5486 -> NEAREST SOLUTION: 0.55

0.5486111111111112

In [37]:
"""
Q6. Tuning hybrid search
The k constant in RRF controls how much the top ranks matter. A smaller k sharpens the gap between positions, so being at the top of a list counts for more. The RRF paper uses 60 as a default, but the best value depends on the data

so let's measure it.
Evaluate hybrid_search over the full ground truth dataset for k values 1, 50, 100, and 200. Compare the MRR values for these runs.

Which k gives the best MRR?

1
50
100
200
Several values of k may give the same MRR. If there's a tie, pick the smallest k.


"""

"\nQ6. Tuning hybrid search\nThe k constant in RRF controls how much the top ranks matter. A smaller k sharpens the gap between positions, so being at the top of a list counts for more. The RRF paper uses 60 as a default, but the best value depends on the data\n\nso let's measure it.\nEvaluate hybrid_search over the full ground truth dataset for k values 1, 50, 100, and 200. Compare the MRR values for these runs.\n\nWhich k gives the best MRR?\n\n1\n50\n100\n200\nSeveral values of k may give the same MRR. If there's a tie, pick the smallest k.\n\n\n"

In [44]:
# different k values: 

hybrid_search_mrr_values = {}

for k in [1, 50, 100, 200]:

    # print which k we are at
    print("k: ", k, "\n")

    # perform hybrid search and compute relevance total
    print("Performing compute_relevance_total with hybrid_search on entire ground_truth data ... ")
    relevance_total = compute_relevance_total(ground_truth=ground_truth, search_function=hybrid_search)
    print("Done.")
    print("relevance_total: ", relevance_total)

    # compute MRR 
    print("Compute MRR ... ")
    mrr_value = mrr(relevance_total)
    print("Done.")
    print("MRR: ", mrr_value)

    # append to results
    hybrid_search_mrr_values[k] = mrr_value

k:  1

Performing compute_relevance_total with hybrid_search on entire ground_truth data ...

  0%|          | 0/360 [00:00<?, ?it/s]

Done.
relevance_total:  [[1, 0, 0, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 1], [0, 1, 0, 0, 1], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 0, 0, 0, 1], [1, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 1], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 1, 0, 0, 0], [1, 1, 1, 0, 0], [0, 1, 1, 0, 0], [1, 1, 0, 1, 0], [0, 0, 0, 0, 1], [0, 0, 0, 1, 0], [1, 1, 1, 1, 1], [1, 1, 1, 0, 0], [1, 0, 1, 0, 0], [1, 0, 1, 0, 0], [0, 0, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 1, 0], [0, 0, 1, 1, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 1, 0], [1, 1, 0, 0, 1], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 1, 0, 1, 1], [1, 1, 0, 1, 0], [1, 1, 1, 0, 1], [1, 1, 1, 1, 0], [1, 1, 1, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 1, 0], [1, 0, 1, 0, 0], [1, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 1], [0, 1, 0, 1, 0], [0, 0, 1, 0, 1], [0, 0, 1, 0, 1], [1, 1, 1, 1, 0], [1, 0, 1, 0, 0], [1, 1, 0, 0, 0], [0, 1, 1, 0, 0], [1, 1, 1, 0, 1], [0, 1, 0, 0, 1], [0, 1, 1, 0, 0], [1, 0, 0, 1, 0], [1, 1, 0, 1, 0], [1, 0, 1, 1, 1], [0, 0, 0, 0, 0], [1, 0, 0, 1, 0], [1, 0, 0, 0, 1], [0, 1, 0, 0, 0], [1, 1, 0, 1, 0], [1, 0, 1, 1, 0], [0, 1, 0, 0, 0], [1, 0, 0, 1, 1], [1, 1, 0, 0, 1], [0, 0, 1, 0, 0], [1, 0, 1, 0, 1], [1, 0, 1, 1, 0], [0, 0, 0, 1, 0], [1, 0, 1, 0, 0], [0, 1, 0, 0, 1], [1, 0, 0, 1, 0], [0, 0, 1, 0, 1], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 1, 0, 0, 0], [1, 0, 0, 1, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 1, 0, 1, 0], [0, 1, 0, 1, 0], [0, 0, 0, 0, 1], [1, 0, 1, 0, 0], [0, 0, 1, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 1, 1], [0, 1, 0, 1, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 1, 0], [0, 0, 0, 1, 0], [0, 1, 0, 1, 0], [0, 0, 0, 0, 1], [1, 0, 0, 1, 0], [1, 0, 1, 1, 0], [1, 0, 1, 1, 1], [0, 0, 0, 0, 0], [1, 0, 1, 1, 1], [1, 0, 1, 0, 0], [1, 1, 1, 1, 1], [0, 1, 0, 0, 0], [1, 0, 1, 0, 1], [1, 0, 0, 1, 0], [1, 1, 1, 0, 0], [1, 1, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 1], [0, 0, 1, 0, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 1, 0, 0, 1], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 1, 0], [1, 1, 0, 1, 0], [1, 1, 0, 1, 0], [1, 0, 0, 1, 1], [1, 1, 0, 0, 1], [1, 1, 1, 0, 0], [1, 1, 1, 1, 0], [0, 0, 0, 0, 0], [1, 0, 1, 1, 0], [1, 1, 1, 0, 1], [0, 0, 1, 0, 1], [0, 0, 1, 1, 0], [1, 0, 0, 0, 0], [0, 1, 1, 0, 0], [0, 1, 0, 0, 1], [0, 0, 0, 1, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 1, 0, 1, 0], [1, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 1, 0], [1, 1, 0, 0, 1], [0, 0, 1, 1, 0], [1, 0, 0, 0, 0], [1, 0, 1, 0, 0], [0, 1, 0, 0, 0], [1, 1, 1, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 1, 0, 1, 1], [0, 0, 0, 0, 0], [1, 1, 0, 1, 0], [0, 0, 1, 1, 0], [1, 1, 0, 0, 0], [0, 1, 0, 1, 1], [0, 1, 0, 0, 0], [0, 1, 1, 1, 0], [0, 1, 1, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [1, 1, 0, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 0, 0], [1, 1, 0, 1, 0], [1, 0, 0, 1, 0], [1, 0, 0, 0, 1], [0, 0, 0, 0, 0], [1, 1, 0, 0, 0], [0, 0, 1, 0, 1], [0, 0, 1, 0, 1], [0, 1, 0, 1, 0], [1, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 1, 0, 1, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 0], [0, 1, 1, 0, 0], [1, 1, 0, 0, 0], [1, 0, 1, 0, 0], [1, 0, 1, 0, 1], [0, 0, 0, 0, 1], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 1], [1, 1, 0, 1, 0], [0, 1, 0, 0, 1], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 0, 0, 0, 1], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 1, 0, 1, 0], [1, 0, 0, 1, 0], [1, 0, 0, 1, 1], [0, 1, 0, 0, 0], [0, 0, 0, 1, 1], [0, 1, 1, 0, 0], [1, 0, 1, 0, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 1, 1, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 1, 0, 1, 0], [0, 0, 1, 1, 0], [1, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 1, 0, 1, 1], [1, 1, 1, 1, 0], [1, 1, 1, 1, 0], [1, 1, 0, 1, 0], [1, 0, 1, 0, 0], [0, 0, 0, 1, 0], [1, 1, 0, 0, 0], [1, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 1, 0], [0, 0, 0, 1, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 1], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [0, 0, 1, 0, 1], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0]]
Compute MRR ...
Done.
MRR:  0.637916666666667
k:  50

Performing compute_relevance_total with hybrid_search on entire ground_truth data ...

  0%|          | 0/360 [00:00<?, ?it/s]

Done.
relevance_total:  [[1, 0, 0, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 1], [0, 1, 0, 0, 1], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 0, 0, 0, 1], [1, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 1], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 1, 0, 0, 0], [1, 1, 1, 0, 0], [0, 1, 1, 0, 0], [1, 1, 0, 1, 0], [0, 0, 0, 0, 1], [0, 0, 0, 1, 0], [1, 1, 1, 1, 1], [1, 1, 1, 0, 0], [1, 0, 1, 0, 0], [1, 0, 1, 0, 0], [0, 0, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 1, 0], [0, 0, 1, 1, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 1, 0], [1, 1, 0, 0, 1], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 1, 0, 1, 1], [1, 1, 0, 1, 0], [1, 1, 1, 0, 1], [1, 1, 1, 1, 0], [1, 1, 1, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 1, 0], [1, 0, 1, 0, 0], [1, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 1], [0, 1, 0, 1, 0], [0, 0, 1, 0, 1], [0, 0, 1, 0, 1], [1, 1, 1, 1, 0], [1, 0, 1, 0, 0], [1, 1, 0, 0, 0], [0, 1, 1, 0, 0], [1, 1, 1, 0, 1], [0, 1, 0, 0, 1], [0, 1, 1, 0, 0], [1, 0, 0, 1, 0], [1, 1, 0, 1, 0], [1, 0, 1, 1, 1], [0, 0, 0, 0, 0], [1, 0, 0, 1, 0], [1, 0, 0, 0, 1], [0, 1, 0, 0, 0], [1, 1, 0, 1, 0], [1, 0, 1, 1, 0], [0, 1, 0, 0, 0], [1, 0, 0, 1, 1], [1, 1, 0, 0, 1], [0, 0, 1, 0, 0], [1, 0, 1, 0, 1], [1, 0, 1, 1, 0], [0, 0, 0, 1, 0], [1, 0, 1, 0, 0], [0, 1, 0, 0, 1], [1, 0, 0, 1, 0], [0, 0, 1, 0, 1], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 1, 0, 0, 0], [1, 0, 0, 1, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 1, 0, 1, 0], [0, 1, 0, 1, 0], [0, 0, 0, 0, 1], [1, 0, 1, 0, 0], [0, 0, 1, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 1, 1], [0, 1, 0, 1, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 1, 0], [0, 0, 0, 1, 0], [0, 1, 0, 1, 0], [0, 0, 0, 0, 1], [1, 0, 0, 1, 0], [1, 0, 1, 1, 0], [1, 0, 1, 1, 1], [0, 0, 0, 0, 0], [1, 0, 1, 1, 1], [1, 0, 1, 0, 0], [1, 1, 1, 1, 1], [0, 1, 0, 0, 0], [1, 0, 1, 0, 1], [1, 0, 0, 1, 0], [1, 1, 1, 0, 0], [1, 1, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 1], [0, 0, 1, 0, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 1, 0, 0, 1], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 1, 0], [1, 1, 0, 1, 0], [1, 1, 0, 1, 0], [1, 0, 0, 1, 1], [1, 1, 0, 0, 1], [1, 1, 1, 0, 0], [1, 1, 1, 1, 0], [0, 0, 0, 0, 0], [1, 0, 1, 1, 0], [1, 1, 1, 0, 1], [0, 0, 1, 0, 1], [0, 0, 1, 1, 0], [1, 0, 0, 0, 0], [0, 1, 1, 0, 0], [0, 1, 0, 0, 1], [0, 0, 0, 1, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 1, 0, 1, 0], [1, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 1, 0], [1, 1, 0, 0, 1], [0, 0, 1, 1, 0], [1, 0, 0, 0, 0], [1, 0, 1, 0, 0], [0, 1, 0, 0, 0], [1, 1, 1, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 1, 0, 1, 1], [0, 0, 0, 0, 0], [1, 1, 0, 1, 0], [0, 0, 1, 1, 0], [1, 1, 0, 0, 0], [0, 1, 0, 1, 1], [0, 1, 0, 0, 0], [0, 1, 1, 1, 0], [0, 1, 1, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [1, 1, 0, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 0, 0], [1, 1, 0, 1, 0], [1, 0, 0, 1, 0], [1, 0, 0, 0, 1], [0, 0, 0, 0, 0], [1, 1, 0, 0, 0], [0, 0, 1, 0, 1], [0, 0, 1, 0, 1], [0, 1, 0, 1, 0], [1, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 1, 0, 1, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 0], [0, 1, 1, 0, 0], [1, 1, 0, 0, 0], [1, 0, 1, 0, 0], [1, 0, 1, 0, 1], [0, 0, 0, 0, 1], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 1], [1, 1, 0, 1, 0], [0, 1, 0, 0, 1], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 0, 0, 0, 1], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 1, 0, 1, 0], [1, 0, 0, 1, 0], [1, 0, 0, 1, 1], [0, 1, 0, 0, 0], [0, 0, 0, 1, 1], [0, 1, 1, 0, 0], [1, 0, 1, 0, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 1, 1, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 1, 0, 1, 0], [0, 0, 1, 1, 0], [1, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 1, 0, 1, 1], [1, 1, 1, 1, 0], [1, 1, 1, 1, 0], [1, 1, 0, 1, 0], [1, 0, 1, 0, 0], [0, 0, 0, 1, 0], [1, 1, 0, 0, 0], [1, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 1, 0], [0, 0, 0, 1, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 1], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [0, 0, 1, 0, 1], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0]]
Compute MRR ...
Done.
MRR:  0.637916666666667
k:  100

Performing compute_relevance_total with hybrid_search on entire ground_truth data ...

  0%|          | 0/360 [00:00<?, ?it/s]

Done.
relevance_total:  [[1, 0, 0, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 1], [0, 1, 0, 0, 1], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 0, 0, 0, 1], [1, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 1], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 1, 0, 0, 0], [1, 1, 1, 0, 0], [0, 1, 1, 0, 0], [1, 1, 0, 1, 0], [0, 0, 0, 0, 1], [0, 0, 0, 1, 0], [1, 1, 1, 1, 1], [1, 1, 1, 0, 0], [1, 0, 1, 0, 0], [1, 0, 1, 0, 0], [0, 0, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 1, 0], [0, 0, 1, 1, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 1, 0], [1, 1, 0, 0, 1], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 1, 0, 1, 1], [1, 1, 0, 1, 0], [1, 1, 1, 0, 1], [1, 1, 1, 1, 0], [1, 1, 1, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 1, 0], [1, 0, 1, 0, 0], [1, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 1], [0, 1, 0, 1, 0], [0, 0, 1, 0, 1], [0, 0, 1, 0, 1], [1, 1, 1, 1, 0], [1, 0, 1, 0, 0], [1, 1, 0, 0, 0], [0, 1, 1, 0, 0], [1, 1, 1, 0, 1], [0, 1, 0, 0, 1], [0, 1, 1, 0, 0], [1, 0, 0, 1, 0], [1, 1, 0, 1, 0], [1, 0, 1, 1, 1], [0, 0, 0, 0, 0], [1, 0, 0, 1, 0], [1, 0, 0, 0, 1], [0, 1, 0, 0, 0], [1, 1, 0, 1, 0], [1, 0, 1, 1, 0], [0, 1, 0, 0, 0], [1, 0, 0, 1, 1], [1, 1, 0, 0, 1], [0, 0, 1, 0, 0], [1, 0, 1, 0, 1], [1, 0, 1, 1, 0], [0, 0, 0, 1, 0], [1, 0, 1, 0, 0], [0, 1, 0, 0, 1], [1, 0, 0, 1, 0], [0, 0, 1, 0, 1], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 1, 0, 0, 0], [1, 0, 0, 1, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 1, 0, 1, 0], [0, 1, 0, 1, 0], [0, 0, 0, 0, 1], [1, 0, 1, 0, 0], [0, 0, 1, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 1, 1], [0, 1, 0, 1, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 1, 0], [0, 0, 0, 1, 0], [0, 1, 0, 1, 0], [0, 0, 0, 0, 1], [1, 0, 0, 1, 0], [1, 0, 1, 1, 0], [1, 0, 1, 1, 1], [0, 0, 0, 0, 0], [1, 0, 1, 1, 1], [1, 0, 1, 0, 0], [1, 1, 1, 1, 1], [0, 1, 0, 0, 0], [1, 0, 1, 0, 1], [1, 0, 0, 1, 0], [1, 1, 1, 0, 0], [1, 1, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 1], [0, 0, 1, 0, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 1, 0, 0, 1], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 1, 0], [1, 1, 0, 1, 0], [1, 1, 0, 1, 0], [1, 0, 0, 1, 1], [1, 1, 0, 0, 1], [1, 1, 1, 0, 0], [1, 1, 1, 1, 0], [0, 0, 0, 0, 0], [1, 0, 1, 1, 0], [1, 1, 1, 0, 1], [0, 0, 1, 0, 1], [0, 0, 1, 1, 0], [1, 0, 0, 0, 0], [0, 1, 1, 0, 0], [0, 1, 0, 0, 1], [0, 0, 0, 1, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 1, 0, 1, 0], [1, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 1, 0], [1, 1, 0, 0, 1], [0, 0, 1, 1, 0], [1, 0, 0, 0, 0], [1, 0, 1, 0, 0], [0, 1, 0, 0, 0], [1, 1, 1, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 1, 0, 1, 1], [0, 0, 0, 0, 0], [1, 1, 0, 1, 0], [0, 0, 1, 1, 0], [1, 1, 0, 0, 0], [0, 1, 0, 1, 1], [0, 1, 0, 0, 0], [0, 1, 1, 1, 0], [0, 1, 1, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [1, 1, 0, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 0, 0], [1, 1, 0, 1, 0], [1, 0, 0, 1, 0], [1, 0, 0, 0, 1], [0, 0, 0, 0, 0], [1, 1, 0, 0, 0], [0, 0, 1, 0, 1], [0, 0, 1, 0, 1], [0, 1, 0, 1, 0], [1, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 1, 0, 1, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 0], [0, 1, 1, 0, 0], [1, 1, 0, 0, 0], [1, 0, 1, 0, 0], [1, 0, 1, 0, 1], [0, 0, 0, 0, 1], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 1], [1, 1, 0, 1, 0], [0, 1, 0, 0, 1], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 0, 0, 0, 1], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 1, 0, 1, 0], [1, 0, 0, 1, 0], [1, 0, 0, 1, 1], [0, 1, 0, 0, 0], [0, 0, 0, 1, 1], [0, 1, 1, 0, 0], [1, 0, 1, 0, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 1, 1, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 1, 0, 1, 0], [0, 0, 1, 1, 0], [1, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 1, 0, 1, 1], [1, 1, 1, 1, 0], [1, 1, 1, 1, 0], [1, 1, 0, 1, 0], [1, 0, 1, 0, 0], [0, 0, 0, 1, 0], [1, 1, 0, 0, 0], [1, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 1, 0], [0, 0, 0, 1, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 1], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [0, 0, 1, 0, 1], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0]]
Compute MRR ...
Done.
MRR:  0.637916666666667
k:  200

Performing compute_relevance_total with hybrid_search on entire ground_truth data ...

  0%|          | 0/360 [00:00<?, ?it/s]

Done.
relevance_total:  [[1, 0, 0, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 1], [0, 1, 0, 0, 1], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 0, 0, 0, 1], [1, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 1], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 1, 0, 0, 0], [1, 1, 1, 0, 0], [0, 1, 1, 0, 0], [1, 1, 0, 1, 0], [0, 0, 0, 0, 1], [0, 0, 0, 1, 0], [1, 1, 1, 1, 1], [1, 1, 1, 0, 0], [1, 0, 1, 0, 0], [1, 0, 1, 0, 0], [0, 0, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 1, 0], [0, 0, 1, 1, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 1, 0], [1, 1, 0, 0, 1], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 1, 0, 1, 1], [1, 1, 0, 1, 0], [1, 1, 1, 0, 1], [1, 1, 1, 1, 0], [1, 1, 1, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 1, 0], [1, 0, 1, 0, 0], [1, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 1], [0, 1, 0, 1, 0], [0, 0, 1, 0, 1], [0, 0, 1, 0, 1], [1, 1, 1, 1, 0], [1, 0, 1, 0, 0], [1, 1, 0, 0, 0], [0, 1, 1, 0, 0], [1, 1, 1, 0, 1], [0, 1, 0, 0, 1], [0, 1, 1, 0, 0], [1, 0, 0, 1, 0], [1, 1, 0, 1, 0], [1, 0, 1, 1, 1], [0, 0, 0, 0, 0], [1, 0, 0, 1, 0], [1, 0, 0, 0, 1], [0, 1, 0, 0, 0], [1, 1, 0, 1, 0], [1, 0, 1, 1, 0], [0, 1, 0, 0, 0], [1, 0, 0, 1, 1], [1, 1, 0, 0, 1], [0, 0, 1, 0, 0], [1, 0, 1, 0, 1], [1, 0, 1, 1, 0], [0, 0, 0, 1, 0], [1, 0, 1, 0, 0], [0, 1, 0, 0, 1], [1, 0, 0, 1, 0], [0, 0, 1, 0, 1], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 1, 0, 0, 0], [1, 0, 0, 1, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 1, 0, 1, 0], [0, 1, 0, 1, 0], [0, 0, 0, 0, 1], [1, 0, 1, 0, 0], [0, 0, 1, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 1, 1], [0, 1, 0, 1, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 1, 0], [0, 0, 0, 1, 0], [0, 1, 0, 1, 0], [0, 0, 0, 0, 1], [1, 0, 0, 1, 0], [1, 0, 1, 1, 0], [1, 0, 1, 1, 1], [0, 0, 0, 0, 0], [1, 0, 1, 1, 1], [1, 0, 1, 0, 0], [1, 1, 1, 1, 1], [0, 1, 0, 0, 0], [1, 0, 1, 0, 1], [1, 0, 0, 1, 0], [1, 1, 1, 0, 0], [1, 1, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 1], [0, 0, 1, 0, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 1, 0, 0, 1], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 1, 0], [1, 1, 0, 1, 0], [1, 1, 0, 1, 0], [1, 0, 0, 1, 1], [1, 1, 0, 0, 1], [1, 1, 1, 0, 0], [1, 1, 1, 1, 0], [0, 0, 0, 0, 0], [1, 0, 1, 1, 0], [1, 1, 1, 0, 1], [0, 0, 1, 0, 1], [0, 0, 1, 1, 0], [1, 0, 0, 0, 0], [0, 1, 1, 0, 0], [0, 1, 0, 0, 1], [0, 0, 0, 1, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 1, 0, 1, 0], [1, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 1, 0], [1, 1, 0, 0, 1], [0, 0, 1, 1, 0], [1, 0, 0, 0, 0], [1, 0, 1, 0, 0], [0, 1, 0, 0, 0], [1, 1, 1, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 1, 0, 1, 1], [0, 0, 0, 0, 0], [1, 1, 0, 1, 0], [0, 0, 1, 1, 0], [1, 1, 0, 0, 0], [0, 1, 0, 1, 1], [0, 1, 0, 0, 0], [0, 1, 1, 1, 0], [0, 1, 1, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [1, 1, 0, 0, 0], [1, 0, 0, 0, 1], [1, 0, 0, 0, 0], [1, 1, 0, 1, 0], [1, 0, 0, 1, 0], [1, 0, 0, 0, 1], [0, 0, 0, 0, 0], [1, 1, 0, 0, 0], [0, 0, 1, 0, 1], [0, 0, 1, 0, 1], [0, 1, 0, 1, 0], [1, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 1], [1, 0, 0, 0, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 1, 0, 1, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 0], [0, 1, 1, 0, 0], [1, 1, 0, 0, 0], [1, 0, 1, 0, 0], [1, 0, 1, 0, 1], [0, 0, 0, 0, 1], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 1], [0, 0, 0, 0, 1], [1, 1, 0, 1, 0], [0, 1, 0, 0, 1], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 0, 0, 0, 1], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 1, 0, 1, 0], [1, 0, 0, 1, 0], [1, 0, 0, 1, 1], [0, 1, 0, 0, 0], [0, 0, 0, 1, 1], [0, 1, 1, 0, 0], [1, 0, 1, 0, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 1, 1, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 1, 0, 1, 0], [0, 0, 1, 1, 0], [1, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 1, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [1, 1, 0, 1, 1], [1, 1, 1, 1, 0], [1, 1, 1, 1, 0], [1, 1, 0, 1, 0], [1, 0, 1, 0, 0], [0, 0, 0, 1, 0], [1, 1, 0, 0, 0], [1, 0, 0, 1, 0], [1, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 1, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 1, 1, 0], [0, 0, 0, 1, 0], [1, 1, 0, 0, 0], [0, 0, 0, 0, 1], [0, 0, 1, 0, 0], [1, 0, 0, 0, 0], [0, 0, 1, 0, 1], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0], [1, 1, 0, 0, 0]]
Compute MRR ...
Done.
MRR:  0.637916666666667

In [45]:
hybrid_search_mrr_values

{1: 0.637916666666667,
 50: 0.637916666666667,
 100: 0.637916666666667,
 200: 0.637916666666667}

In [ ]:
# sort dictionary: Which k gives the best MRR?

sorted_k = sorted(
    hybrid_search_mrr_values,
    key=hybrid_search_mrr_values.get,
    reverse=True    
)

sorted_k

# -> SOLUTION with: Several values of k may give the same MRR. If there's a tie, pick the smallest k. 
# -> 1

[1, 50, 100, 200]